var sparkConfig={gateway:null,servers:null,users:null,config:function(c,a,b,e,d,f){c=c+"/CONF?type="+a+"&action="+b;f&&(c+=f);hi5.tool.openWebSocket(c,d,e)},showMessage:function(c){document.getElementById("message").innerHTML=c},checkError:function(c){if(c.error){var a=__svi18n.errorCode["S"+c.name];c.message&&(a+=c.message);setTimeout(function(){alert(a)},0);return!0}return!1},refreshServers:function(){function c(){var a=sparkConfig.servers.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),
"servers","remove",b,null,"&id="+a)}function a(){var a=this.getValue(0);sparkConfig.editServer(a)}function b(b){sparkConfig.servers=b;var d=new hi5.DataTable(b),f=new hi5.DataGrid(document.getElementById("servers.rows"));f.dataTable=d;f.open();document.getElementById("servers.type").value=b.type;document.getElementById("servers.display").checked=b.display;f.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};d.addEvent("beforeremove",c);d.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),
"servers","get",b)},refreshUsers:function(){function c(){var a=sparkConfig.users.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"users","remove",b,null,"&name="+a)}function a(){var a=this.getValue(0);sparkConfig.editUser(a)}function b(b){sparkConfig.users=b;var d=new hi5.DataTable(b),b=new hi5.DataGrid(document.getElementById("users.rows"));b.dataTable=d;b.open();b.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};d.addEvent("beforeremove",c);d.addEvent("onaction",
a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"users","get",b)},initUI:function(){function c(){var c="&sType="+a.value+"&display="+b.checked;sparkConfig.config(sparkConfig.getGatewayAddr(),"servers_h","put",function(){},null,c)}var a=document.getElementById("servers.type"),b=document.getElementById("servers.display");a.onchange=c;b.onchange=c;document.getElementById("conf3").addEvent("ontabchange",function(a){sparkConfig.gateway.prop.webfeed&&(document.getElementById("servers.add").style.disabled=
!0,document.getElementById("users.add").style.disabled=!0);switch(a){case 1:if(sparkConfig.servers)break;sparkConfig.refreshServers();break;case 2:if(sparkConfig.users)break;sparkConfig.refreshUsers()}});var e=hi5.tool.queryToObj(),d=e.port,e=e.expect;if(d){var f=window.location.host,g=location.protocol;f||(f="localhost");document.getElementById("gateway").value=f;f=g+"//"+f;e&&(document.getElementById("expectAddr").innerHTML=f+":"+e,document.getElementById("expect").style.display="inline");if("http:"==
g&&"80"!=d||"https:"==g&&"443"!=d)f+=":"+d;document.getElementById("sparkAddr").innerHTML="<a href='"+f+"'>"+f+"</a>";document.getElementById("conf1").style.display="block"}else document.getElementById("gateway").value=location.host,document.getElementById("conf0").style.display="block"},getGatewayAddr:function(){return("http:"==location.protocol?"ws:":"wss:")+"//"+document.getElementById("gateway").value},getAll:function(){sparkConfig.config(sparkConfig.getGatewayAddr(),"gateway","get",function(c){if(!sparkConfig.checkError(c)){sparkConfig.gateway=
c;var c=c.prop,a,b,e=document.getElementById("frmGateway").elements;for(b in c)if(a=e[b]){var d=c[b];"checkbox"==a.type?a.checked="true"===d:a.value=d}document.getElementById("conf3").style.display="block"}})},saveGateway:function(){(function(c,a){for(var b=c.elements,e=0,d=b.length;e<d;e++){var f=b[e];if(f){var g=f.value;if(""!==g){var h=f.type;"button"==h||"submit"==h||(a[f.name]="checkbox"==h?f.checked+"":g)}}}})(document.getElementById("frmGateway"),sparkConfig.gateway.prop);sparkConfig.config(sparkConfig.getGatewayAddr(),
"gateway","put",function(c){var a;c.error?(a=__svi18n.errorCode["S"+c.name],c.message&&(a+=c.message)):a=__svi18n.info.restart;setTimeout(function(){alert(a)},0)},JSON.stringify(sparkConfig.gateway))},editServer:function(c,a){function b(b){var c=b.rdp;c||(c={});c.id=b.id;c.displayName=b.displayName;b.server&&(c.server=b.server);b.icon&&(c.icon=b.icon);if(c.mapDisk&&c.disks){for(var b=c.disks,g,h=Math.min(3,b.length),i=0;i<h;i++)c["dosName"+i]=b[i].dosName,c["devicePath"+i]=b[i].devicePath,g=b[i].actions,
c["actRedirect"+i]=0!=(g&1),c["actDownload"+i]=0!=(g&2),c["actUpload"+i]=0!=(g&4);delete c.disks}e.reset();hi5.browser.objToForm(c,e);a?(hi5.$("server.id").value=d,hi5.$("server.displayName").value=f):e._dataAction="put"}var e=document.getElementById("servers.view"),d="",f="";a&&(d=hi5.$("server.id").value,f=hi5.$("server.displayName").value);a||e.reset();var g=e.visible?e:new hi5.Lightbox(e);g.onclose=function(){sparkConfig.refreshServers()};sparkConfig.showMessage("");g.visible()||g.show();e._dataAction=
"post";c&&sparkConfig.config(sparkConfig.getGatewayAddr(),"server","get",b,null,"&id="+c);var h=hi5.$("server.server");h.hide||new hi5.Select(h);h.beforedropdown=function(){for(var a=h.options,b=sparkConfig.servers.rows,c=a.length=0,d=b.length;c<d;c++)a[c]=new Option(b[c][1],b[c][0])};h.onchange=function(){sparkConfig.editServer(h.value,true)}},editUser:function(c){var a=document.getElementById("users.view");a.reset();var b=new hi5.Lightbox(a);b.onclose=function(){sparkConfig.refreshUsers()};sparkConfig.showMessage("");
b.show();a._dataAction="post";c&&(a._dataAction="put",c={name:c,password:sparkConfig.users.getValue(0),servers:sparkConfig.users.getValue(2)},hi5.browser.objToForm(c,a))},saveServer:function(){var c=document.getElementById("servers.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);if(a.mapDisk){var b=0,e=[];a.dosName0&&(a.actRedirect0&&(b|=1),a.actDownload0&&(b|=2),a.actUpload0&&(b|=4),e.push({dosName:a.dosName0,devicePath:a.devicePath0,actions:b}),delete a.dosName0,delete a.devicePath0);
a.dosName1&&(b=0,a.actRedirect1&&(b|=1),e.push({dosName:a.dosName1,devicePath:a.devicePath1,actions:b}),delete a.dosName1,delete a.devicePath1);a.dosName2&&(b=0,a.actRedirect2&&(b|=1),e.push({dosName:a.dosName2,devicePath:a.devicePath2,actions:b}),delete a.dosName2,delete a.devicePath2);0<e.length&&(a.disks=e)}b={};b.id=a.id;b.displayName=a.displayName;a.server&&(b.server=a.server);a.icon&&(b.icon=a.icon);b.rdp=a;sparkConfig.config(sparkConfig.getGatewayAddr(),"server",c._dataAction||"put",function(a){if(a.error)sparkConfig.showMessage(a.message);
else{c.reset();c._dataAction="post";sparkConfig.gateway.server||sparkConfig.getAll()}},JSON.stringify(b));return!1},saveUser:function(){var c=document.getElementById("users.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);if(a.servers){for(var b=a.servers.split(","),e=b.length,d=0;d<e;d++)b[d]=b[d].trim();a.servers=b}sparkConfig.config(sparkConfig.getGatewayAddr(),"user",c._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(c.reset(),c._dataAction="post",sparkConfig.gateway.user||
sparkConfig.getAll())},JSON.stringify(a));return!1}};window.addEventListener("load",sparkConfig.initUI,!1);
