"undefined"==typeof hi5&&(hi5={});hi5.init={funcs:[],push:function(a){hi5.init.funcs.push(a)},start:function(){for(var a=hi5.init.funcs,b=0,d=a.length;b<d;b++)a[b]()}};String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Number.prototype.toShort=function(){var a=this&65535;return a>32767?a-65536:this};Number.prototype.toByte=function(){var a=this&255;return a>127?a-256:a};
String.prototype.applyArgs=function(a){for(var b=this.split("%"),d,e,c=b[0],f=1,g=b.length;f<g;f++){d=b[f];var i=parseInt(d);if(isNaN(i))c=c+d;else{e=d.substring((i+"").length);(d=a[i-1])&&(c=c+d);c=c+e}}return c};Array.prototype.removeElm=function(a){a=this.indexOf(a);a!=-1&&this.splice(a,1)};Array.prototype.fill=function(a){for(var b=this.length;--b>=0;)this[b]=a};
Date.prototype.getStdTimezoneOffset=function(){var a=new Date(this.getFullYear(),0,1),b=new Date(this.getFullYear(),6,1);return Math.max(a.getTimezoneOffset(),b.getTimezoneOffset())};hi5.WebSocket=window.WebSocket||window.MozWebSocket;hi5.$=function(a){return document.getElementById(a)};hi5.callback={callbacks:{},no:0,put:function(a){var b="CB"+this.no++;this.callbacks[b]=a;return b},get:function(a){var b=this.callbacks[a];b&&delete this.callbacks[a];return b}};
hi5.tool={isNumber:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},getMousePos:function(a){var b=0,d=0;if(!a)a=window.event;if(a.pageX){b=a.pageX;d=a.pageY}else if(a.clientX){b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft;d=a.clientY+document.body.scrollTop+document.documentElement.scrollTop}return{x:b,y:d}},getPos:function(a){var b=0,d=0;if(a.offsetParent){do{b=b+a.offsetLeft;d=d+a.offsetTop}while(a=a.offsetParent)}return{x:b,y:d}},bytesToSize:function(a){if(isNaN(a))return"";
var b=Math.floor(Math.log(+a)/Math.log(2));b<1&&(b=0);b=Math.floor(b/10);a=+a/Math.pow(2,10*b);a.toString().length>a.toFixed(3).toString().length&&(a=a.toFixed(3));return a+[" bytes"," KB"," MB"," GB"," TB"," PB"," EB"," ZB"," YB"][b]},queryToObj:function(a){a||(a=location.search.substring(1));var b={};if(a)for(var a=a.split("&"),d=a.length,e=0;e<d;e++){var c=a[e].split("=");b[c[0]]=decodeURIComponent(c[1])}return b},disableInput:function(){var a=document.createElement("div");a.style.position="fixed";
a.style.left=0;a.style.top=0;a.style.width="100%";a.style.height="100%";a.style.zIndex=99999;a.style.background="url(spinner.gif) no-repeat center center";document.documentElement.appendChild(a);window.__hi5_bk=a},enableInput:function(){if(window.__hi5_bk){document.documentElement.removeChild(window.__hi5_bk);window.__hi5_bk=null}},scale:function(a,b){b="scale("+b+")";a.style.transform=b;a.style.mozTransform=b;a.style.webkitTransform=b;a.style.msTransform=b;a.style.oTransform=b},openWebSocket:function(a,
b,d){var e=false;if(d){d=hi5.callback.put(d);a=a+("&callback="+d)}var c=new hi5.WebSocket(a);c.onopen=function(){e=true;b&&c.send(b)};c.onclose=function(){e||alert(__svi18n.errorCode.connection)};c.onmessage=function(a){c.close();a=JSON.parse(a.data);a.callback?hi5.callback.get(a.callback)(a):console.log(a)};return c},getChildNodesByTag:function(a,b){for(var d=a.childNodes,e=[],c=0,f=d.length;c<f;c++)d[c].nodeName.toLowerCase()==b&&e.push(d[c]);return e},arraycopy:function(a,b,d,e,c){for(var f=0;f<
c;f++)d[e+f]=a[b+f]},hasProperty:function(a,b){return b in a||b in a.prototype?true:b in(a.__proto__||a.constructor.prototype)},isCapslock:function(a){var b=String.fromCharCode(a.keyCode||a.which);return b.toUpperCase()===b&&b.toLowerCase()!==b&&!a.shiftKey?true:false}};
hi5.browser=function(){var a=navigator.userAgent,b={isTouch:"createTouch"in document||a.indexOf("Mobile")!=-1,isFirefox:a.indexOf("Firefox")!=-1,isOpera:a.indexOf("Opera")!=-1,isRIM:a.indexOf(" RIM ")!=-1};b.isMultitask=!(b.isTouch&&a.indexOf("Mac OS")!=-1);b.binaryWS=function(a){var b=false;try{var c=new hi5.WebSocket(a||"ws://localhost"),b="binaryType"in c;c.close()}catch(f){}return b};b.cookie2Obj=function(){var a=document.cookie;if(a=="")return null;for(var b={},c,f=a.split(";"),g=0,i=f.length;g<
i;g++){for(var h=f[g];h.charAt(0)==" ";)h=h.substring(1,h.length);a=h.indexOf("=");if(a>0){c=decodeURIComponent(h.substring(a+1).replace(/\+/g," "));hi5.tool.isNumber(c)&&(c=parseFloat(c));if(c==="true"||c==="on")c=true;else if(c==="false"||c==="off")c=false;b[h.substring(0,a)]=c}}return b};b.getLibPath=function(a){for(var b=document.getElementsByTagName("script"),c,f,g=null,i=b.length,h=0;h<i;h++){f=b[h].src;c=f.indexOf(a);if(c>-1){g=f.substring(0,c);break}}return g};b.loadJS=function(a){a.indexOf("/")<
0&&(a=hi5.libPath+a);getLibPath(a)||document.writeln('<script type="text/javascript" src="'+a+'"><\/script>')};b.formToObj=function(a,b){var c=a.elements,f,g,i,h=c.length;b||(b={});for(var j=0;j<h;j++){f=c[j];i=f.name;g=f.type;switch(g){case "button":continue;case "checkbox":f=f.checked;break;case "raido":if(!f.checked)continue;f=f.checked;break;case "number":parseFloat(f.value);default:f=f.value}f!==""&&(b[i]=f)}return b};b.objToForm=function(a,b){var c,f,g=b.elements,i;for(i in a)if(c=g[i]){f=a[i];
typeof f=="boolean"?c.checked=f:c.value=f}};return b}();hi5.libPath=hi5.browser.getLibPath("hi5_min.js");hi5.libPath||(hi5.libPath=hi5.browser.getLibPath("hi5.js"));
hi5.EventControl=function(a){a.addEvent=function(b,d){if(!a[b]||!a[b]._evt_listeners){a[b]=function(){a.fireEvent(b,arguments)};a[b]._evt_listeners=[]}a[b]._evt_listeners.push(d)};a.removeEvent=function(b,d){if(!a[b]&&!a[b]._evt_listeners)return false;var e=a[b]._evt_listeners,c=e.indexOf(d);if(c>-1){e.removeElm(c);return true}return false};a.fireEvent=function(b,d){if(a[b]&&a[b]._evt_listeners){var e=a[b]._evt_listeners;d||(d=[]);for(var c=0,f=e.length;c<f;c++)e[c].apply(a,d)}};return a};
hi5.Dragable=function(a){function b(b){b.preventDefault&&b.preventDefault();b.touches&&(b=b.touches.length==1?b.touches[0]:b.changedTouches[0]);var b=e(b),c=b.y-d.y;a.style.left=a.offsetLeft+(b.x-d.x)+"px";a.style.top=a.offsetTop+c+"px";d.x=b.x;d.y=b.y}a.draggable=true;var d={},e=hi5.tool.getMousePos,c=hi5.browser.isTouch;a.addEventListener(c?"touchstart":"dragstart",function(a){a.stopPropagation&&a.stopPropagation();a.touches&&(a=a.touches[0]);d=e(a)},false);a.addEventListener(c?"touchend":"dragend",
function(b){b.stopPropagation&&b.stopPropagation();if(!b.touches){var b=e(b),c=b.y-d.y;a.style.left=a.offsetLeft+(b.x-d.x)+"px";a.style.top=a.offsetTop+c+"px"}},false);c&&a.addEventListener("touchmove",b,false);return a};
hi5.Fadable=function(a,b,d){function e(){document.activeElement==a.activeObj?setTimeout(e,i):a.style.display="none"}function c(){a.style.display=g;if(j){h!=null&&clearTimeout(h);h=setTimeout(e,i)}}if(a.tabIndex<0)a.tabIndex=999;var f=d||document,g=a.style.display,i=b||3E3,h=null,j=true;a.setFadable=function(b){(j=b)?f.addEventListener(hi5.browser.isTouch?"touchend":"mouseup",c,false):a.style.display=g};a.startFade=c};
hi5.Toolbar=function(){var a=document.createElement("div");a.className="toolbar";a.addButton=function(b,d){var e=document.createElement("img");b.indexOf("/")<0&&(b=hi5.libPath+b);e.src=b;e.onclick=d;a.appendChild(e);return e};a.resize=function(){var b=window.innerWidth,d=(b-a.offsetWidth)/2>>0;if(d<100||d>b-100)d=b/2-20>>0;a.style.top=0;a.style.left=d+"px"};a.removeButton=function(b){for(var d=a.getElementsByTagName("img"),e=d.length,c=0;c<e;c++)if(d[c].src.indexOf(b)>=0){a.removeChild(d[c]);e==1&&
a.parentNode.removeChild(a);break}};return a};hi5.ProgressBar=function(a){a.progress=0;a.maxValue=0;var b=a.getElementsByTagName("div")[0];a.setProgress=function(d){d=Math.floor(d/a.maxValue*100);if(d!=a.progress){a.progress=d;b.style.width=d/100*a.offsetWidth+"px"}};return a};
hi5.Lightbox=function(a,b){function d(){var b=e.clientWidth,c=e.clientHeight,d=a.offsetWidth,g=a.offsetHeight;if(d>b*0.96){d=b*0.96;a.style.width=d+"px"}if(g>c*0.96){g=c*0.96;a.style.height=g+"px";a.style.width=a.offsetWidth+22+"px"}b=(b-d)/2;c=(c-g)/3;a.style.left=b+"px";a.style.top=c+"px";f.style.left=b+a.offsetWidth-6+"px";f.style.top=c-6+"px"}var e=document.createElement("div");e.style.position="fixed";e.style.left=0;e.style.top=0;e.style.width="100%";e.style.height="100%";e.style.zIndex=999;
e.style.backgroundColor="#222";b||(b=0.4);e.style.opacity=b;var c=a.style.display;a.style.position="absolute";a.style.zIndex=1E3;a.style.visibility="hidden";var f=document.createElement("div");f.style.position="absolute";var g=document.createElement("img");g.width=25;g.height=25;g.src=hi5.appcfg&&hi5.appcfg.img&&hi5.appcfg.img.close?hi5.appcfg.img.close:hi5.libPath+"del.png";g.style.cursor="pointer";f.style.zIndex=10001;g.align="top";f.appendChild(g);a.resize=d;a.show=function(){var b=document.documentElement;
b.appendChild(e);b.appendChild(f);a.style.display="block";a.style.visibility="visible";d()};a.visible=function(){return a&&a.style.visibility=="visible"};a.dismiss=function(b){function d(){var b=document.documentElement;b.removeChild(e);b.removeChild(f);a.style.visibility="hidden";a.style.display=c;if(a.onclose)a.onclose()}b?setTimeout(d,b):d()};a.background=e;g.addEventListener("click",a.dismiss,false);return a};
hi5.DataTable=function(a){hi5.EventControl(a);typeof a==="string"&&(a=JSON.parse(a));var b=a.rows,d=a.cols;a.rowNo=-1;a.beforeGetValue=null;a.moveTo=function(b){a.rowNo=b};a.getColNo=function(a){for(var b=0,f=d.length;b<f;b++)if(d[b].name===a)return b;return-1};a.getValue=function(d){var c=b[a.rowNo][d];return a.beforeGetValue==null?c:a.beforeGetValue(d,c)};a.setValue=function(d,c){b[a.rowNo][d]=c;a.fireEvent("onchange",[d,a.rowNo,c])};a.first=function(){a.moveTo(0)};a.next=function(){a.moveTo(a.rowNo+
1)};a.last=function(){a.moveTo(b.length-1)};a.hasNext=function(){return a.rowNo<b.length-1};a.remove=function(d){if(!d)d=a.rowNo;var c=[d];a.fireEvent("beforeremove",c);b.splice(d,1);a.fireEvent("onremove",c)};a.perform=function(b){typeof a[b]=="function"?a[b].apply(a):a.fireEvent("onaction",[b])};a.fireEvent("onopen");return a};
hi5.DataGrid=function(a){function b(b){var c=this.rowIndex;if(typeof c=="number"){d=c=c-a.tHead.rows.length;a.dataTable.moveTo(c)}if(a.onrowclick)a.onrowclick(b)}if("TABLE"!=a.nodeName)throw"Not HTML Table";a.dataTable=null;a.onrowclick=null;var d=-1;a.getValue=function(b){var c=a.dataTable;c.moveTo(d);return c.getValue(c.getColNo(b))};a.fillData=function(e){var c=e.rows,f=e.cols.length,g=a.tBodies[0],i,h,j,l;if(!a._rowTemp)a._rowTemp=a.tBodies[0].rows[0].cloneNode(true);l=a._rowTemp;var k,m=g.cloneNode(false),
n;h=c.length;for(i=0;i<h;i++){k=l.cloneNode(true);n=k.cells;e.moveTo(i);for(c=0;c<f;c++){j=e.getValue(c);a.beforeDisplayValue&&(j=a.beforeDisplayValue(c,j));n[c].innerHTML=j}d=i;k.addEventListener("click",b,false);a.beforeAppendRow&&a.beforeAppendRow(k);m.appendChild(k)}a.removeChild(g);a.appendChild(m)};a.open=function(){if(a.dataTable!=null){a.fillData(a.dataTable);a.dataTable.addEvent("onremove",function(b){var c=a.tBodies[0];(b=c.rows[b])&&c.removeChild(b)})}};return a};
hi5.Select=function(a){var b=a.parentNode,d=document.createElement("div");d.style.padding="0";d.style.display="inline";b.insertBefore(d,a);var e=document.createElement("img");e.src="select.png";e.height=a.offsetHeight;e.style.verticalAlign="-6px";d.appendChild(a);d.appendChild(e);var c=document.createElement("select"),b=a.getAttribute("hi5_size");c.size=b?b:10;if(b=a.getAttribute("hi5_list")){b=b.split(";");d=b.length;if(d>0)for(var f=c.options,g=0;g<d;g++)f[g]=new Option(b[g])}c.style.position="absolute";
c.style.zIndex=99999;c.style.visibility="hidden";document.documentElement.appendChild(c);a.show=function(){a.beforedropdown&&a.beforedropdown(a);c.style.visibility="visible";c.focus()};a.hide=function(){c.style.visibility="hidden";a.focus()};e.onclick=function(){if(c.style.visibility=="hidden"){if(c.options.length==0){var b=a.getAttribute("onfetchlist");b&&eval(b)}b=hi5.tool.getPos(a);c.style.left=b.x+"px";c.style.top=b.y+a.offsetHeight+"px";c.style.width=a.offsetWidth+e.width+3+"px";a.show()}else a.hide()};
c.onchange=function(){a.value=c.value;c.style.visibility="hidden";if(a.onchange)a.onchange()};a.options=c.options;return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("Hi5Select"),b=a.length,d=0;d<b;d++)new hi5.Select(a[d])});
hi5.Tab=function(a){function b(b){var c=f;if(f!=b){g[f].className="tab_back";i[f].className="tab_hide";f=b}g[b].className="tab_front";i[b].className="tab_show";g[b].focus();c!=b&&a.fireEvent("ontabchange",[b,c])}function d(a){a=g.indexOf(a.target);a!=-1&&b(a)}hi5.EventControl(a);for(var e=a.getElementsByClassName("tab")[0].getElementsByClassName("tab_title")[0].childNodes,c=e.length,f=0,g=[],i=[],h=0;h<c;h++){var j=e[h];if(j.nodeName.toUpperCase()=="SPAN"){j.className="tab_back";j.onclick=d;j.onfocus=
d;g[g.length]=j}}e=a.getElementsByClassName("tab_body")[0].childNodes;c=e.length;for(h=0;h<c;h++){j=e[h];if(j.nodeName.toUpperCase()=="DIV"){i[i.length]=j;j.className="tab_hide"}}b(f);a.setSelected=b;a.getSelected=function(){return f};return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("tab_all"),b=a.length,d=0;d<b;d++)new hi5.Tab(a[d])});hi5.graphic={};
hi5.graphic.Rectangle=function(a,b,d,e){this.x=a;this.y=b;this.width=d;this.height=e;this.union=function(a,b,d,e){var h=this.width,j=this.height;if((h|j)<0){this.x=a;this.y=b;this.width=d;this.height=e}else if(!((d|e)<0)){var l=this.x,k=this.y,h=h+l,j=j+k,d=d+a,e=e+b;l>a&&(l=a);k>b&&(k=b);h<d&&(h=d);j<e&&(j=e);this.x=l;this.y=k;this.width=h-l;this.height=j-k}}};
hi5.init.push(function(){function a(d){function e(a,b){g=document.createElement("img");g.src=hi5.libPath+a;g.className="hi5_notifer_button";g.onclick=function(a){b.apply(c,[a])};return g}var c=document.createElement("div");c.className="hi5_notifer";var f=document.createElement("div");f.className="hi5_notifer_title";var g,i=document.createElement("img");i.src=hi5.libPath+"info.png";i.className="hi5_notifer_icon";f.appendChild(i);f.appendChild(document.createTextNode(d.title?d.title:""));c.appendChild(f);
f=document.createElement("div");f.appendChild(document.createTextNode(d.msg));c.countNode=document.createElement("span");c.countNode.className="hi5_notifer_count";f.appendChild(c.countNode);d.cbNo&&f.appendChild(e("del.png",d.cbNo));d.cbYes&&f.appendChild(e("ok.png",d.cbYes));c.title=d.title;c.message=d.msg;c.msgCount=1;c.addCount=function(){c.msgCount++;c.countNode.innerHTML="("+c.msgCount+")"};c.appendChild(f);c.destroy=function(){if(c.parentNode){c.parentNode.removeChild(c);var d=b.notifyPool.shift();
d&&b.appendChild(new a(d))}};d.timeout&&setTimeout(function(){c.destroy()},d.timeout);if(!d.cbYes&&!d.cbNo)c.onclick=c.destroy;return c}var b=hi5.$("hi5_notifer_all");if(!b){b=document.createElement("div");b.id="hi5_notifer_all";document.documentElement.appendChild(b)}b.notifyPool=[];b.getNotifier=function(a,e){for(var c=b.getElementsByTagName("div"),f=0,g=c.length;f<g;f++)if(c[f].title==a&&c[f].message==e)return c[f];return null};b.notify=function(d){var e=b.getNotifier(d.title,d.msg);e?e.addCount():
hi5.tool.getChildNodesByTag(b,"div").length<3?b.appendChild(new a(d)):b.notifyPool.push(d)};hi5.notifications=b});document.addEventListener("DOMContentLoaded",hi5.init.start,!1);
