function connvertServer(m){var o={};o.id=m.id;o.server=m.id;o.displayName=m.displayName||m.id;(m=m.rdp)||(m={});o.port=m.port||3389;o.user=m.username||"";o.pwd=m.password||"";o.domain=m.domain||"";o.keyboard=1033;o.useConsole=m.console||!1;o.legacyMode=m.leagacyMode||m.legacyMode||!1;o.server_bpp=m.color||16;o.playSound=m.playSound||0;o.mapClipboard=m.mapClipboard||!0;o.playSound=m.playSound||0;o.mapPrinter=m.mapPrinter||!0;o.mapDisk=m.mapDisk||!0;o.command=m.command||"";o.directory=m.directory||
"";o.exe=m.remoteProgram||"";o.args=m.remoteArgs||"";o.startProgram=0<o.exe.length?"app":0<o.command.length?"shell":"noapp";return o}
function getServers(m,o){var u=Connection.getValue(Connection.KEY_TIMESTAMP),p=new hi5.WebSocket(m+(null==u?"":"?since="+u)),x=!1,v=!1;p.onmessage=function(m){x=!0;1<svGlobal.log&&console.log(m.data);m=JSON.parse(m.data);m.lastModified&&Connection.setValue(Connection.KEY_TIMESTAMP,m.lastModified+"");if(m=m.connections)for(var o=0,u=m.length;o<u;o++){var C=m[o];null==Connection.getValue(C.id)&&(Connection.save(C.id,connvertServer(C)),v=!0)}p.close()};p.onclose=function(){o(v,x)}}
var svManager={getInstance:function(){return"rdpConnection"in window&&rdpConnection.running()?rdpConnection:null}};svGlobal.getInstance=svManager.getInstance;
window.addEventListener("beforeunload",function(m){var o=svManager.getInstance();if(null==o)return null;var o=o.getRunninApps(),u=o.length;if(0<u){for(var p=__svi18n.remoteApp.warn+"\n\n",x=0;x<u;x++)p+=o[x]+"\n";p+="\n"+__svi18n.remoteApp.close+"\n";hi5.browser.isFirefox&&hi5.notifications.notify({msg:p});m&&(m.returnValue=p);return p}return null},!1);
function Rdp2(m){if(!m){var o=window.opener;try{if(o&&o.__sparkUser&&o.__sparkUser.server&&(m=o.__sparkUser.server),!m&&o.sparkServer)m=o.sparkServer}catch(u){}m||(m=hi5.browser.cookie2Obj());if(!m)return alert(__svi18n.noauth),null}var p=o="",x=window.innerWidth,v=window.innerHeight,D=16,J=null,ea;for(ea in m){""!=o&&(o+="&");var C=m[ea];if("useSSL"==ea)J="true"===C;else{if("boolean"==typeof C)if(C)C="on";else continue;o+=ea+"="+encodeURIComponent(C);switch(ea){case "gateway":p=C;break;case "width":x=
parseInt(C);break;case "height":v=parseInt(C);break;case "color":D=parseInt(C)}}}null===J&&(J="https:"==location.protocol);return new Rdp((J?"wss://":"ws://")+p+"/RDP?"+o,x,v,D)}svGlobal.Rdp2=Rdp2;
function Rdp(m,o,u,p){var x,v,D,J;function ea(){function a(a){for(var b,d=0,c=0;320>c;c++)b=a[c],r[d++]=b&255,r[d++]=b>>8&255;return r}function b(a,b){var d=Array(8),e=Array(4),j=Array(4),i=Array(4),h=Array(4),f=Array(52),k=b,g=0,g=a[k++]&255;d[0]=g&63;g=(65535&g)>>>6|a[k++]<<2&1023;d[1]=g&63;g=(65535&g)>>>6|a[k++]<<4&4095;d[2]=g&31;g=(65535&g)>>>5;d[3]=g&31;g=(65535&g)>>>5|a[k++]<<2&1023;d[4]=g&15;g=(65535&g)>>>4;d[5]=g&15;g=(65535&g)>>>4|a[k++]<<2&1023;d[6]=g&7;g=(65535&g)>>>3;d[7]=g&7;g=(65535&
g)>>>3|a[k++]<<4&4095;e[0]=g&127;g=(65535&g)>>>7;i[0]=g&3;g=(65535&g)>>>2;j[0]=g&3;g=(65535&g)>>>2|a[k++]<<1&511;h[0]=g&63;f[0]=(65535&g)>>>6&7;g=a[k++]&255;f[1]=g&7;g=(65535&g)>>>3;f[2]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[3]=g&7;g=(65535&g)>>>3;f[4]=g&7;g=(65535&g)>>>3;f[5]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[6]=g&7;g=(65535&g)>>>3;f[7]=g&7;f[8]=(65535&g)>>>3&7;g=a[k++]&255;f[9]=g&7;g=(65535&g)>>>3;f[10]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[11]=g&7;g=(65535&g)>>>3;f[12]=g&7;g=(65535&g)>>>3|a[k++]<<
4&4095;e[1]=g&127;g=(65535&g)>>>7;i[1]=g&3;g=(65535&g)>>>2;j[1]=g&3;g=(65535&g)>>>2|a[k++]<<1&511;h[1]=g&63;f[13]=(65535&g)>>>6&7;g=a[k++]&255;f[14]=g&7;g=(65535&g)>>>3;f[15]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[16]=g&7;g=(65535&g)>>>3;f[17]=g&7;g=(65535&g)>>>3;f[18]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[19]=g&7;g=(65535&g)>>>3;f[20]=g&7;f[21]=(65535&g)>>>3&7;g=a[k++]&255;f[22]=g&7;g=(65535&g)>>>3;f[23]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[24]=g&7;g=(65535&g)>>>3;f[25]=g&7;g=(65535&g)>>>3|a[k++]<<4&
4095;e[2]=g&127;g=(65535&g)>>>7;i[2]=g&3;g=(65535&g)>>>2;j[2]=g&3;g=(65535&g)>>>2|a[k++]<<1&511;h[2]=g&63;f[26]=(65535&g)>>>6&7;g=a[k++]&255;f[27]=g&7;g=(65535&g)>>>3;f[28]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[29]=g&7;g=(65535&g)>>>3;f[30]=g&7;g=(65535&g)>>>3;f[31]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[32]=g&7;g=(65535&g)>>>3;f[33]=g&7;f[34]=(65535&g)>>>3&7;g=a[k++]&255;f[35]=g&7;g=(65535&g)>>>3;f[36]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[37]=g&7;g=(65535&g)>>>3;f[38]=g&7;g=(65535&g)>>>3|a[k++]<<4&4095;
e[3]=g&127;g=(65535&g)>>>7;i[3]=g&3;g=(65535&g)>>>2;j[3]=g&3;g=(65535&g)>>>2|a[k++]<<1&511;h[3]=g&63;f[39]=(65535&g)>>>6&7;g=a[k++]&255;f[40]=g&7;g=(65535&g)>>>3;f[41]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[42]=g&7;g=(65535&g)>>>3;f[43]=g&7;g=(65535&g)>>>3;f[44]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[45]=g&7;g=(65535&g)>>>3;f[46]=g&7;f[47]=(65535&g)>>>3&7;g=a[k++]&255;f[48]=g&7;g=(65535&g)>>>3;f[49]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[50]=g&7;g=(65535&g)>>>3;f[51]=g&7;g=(65535&g)>>>3;c(d,e,j,i,h,f,q,
0);g=g&15|a[k++]<<4&4095;d[0]=g&63;d[1]=(65535&g)>>>6&63;g=a[k++]&255;d[2]=g&31;g=(65535&g)>>>5|a[k++]<<3&2047;d[3]=g&31;g=(65535&g)>>>5;d[4]=g&15;g=(65535&g)>>>4|a[k++]<<2&1023;d[5]=g&15;g=(65535&g)>>>4;d[6]=g&7;d[7]=(65535&g)>>>3&7;g=a[k++]&255;e[0]=g&127;g=(65535&g)>>>7|a[k++]<<1&511;i[0]=g&3;g=(65535&g)>>>2;j[0]=g&3;g=(65535&g)>>>2|a[k++]<<5&8191;h[0]=g&63;g=(65535&g)>>>6;f[0]=g&7;g=(65535&g)>>>3;f[1]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[2]=g&7;g=(65535&g)>>>3;f[3]=g&7;f[4]=(65535&g)>>>3&7;g=a[k++]&
255;f[5]=g&7;g=(65535&g)>>>3;f[6]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[7]=g&7;g=(65535&g)>>>3;f[8]=g&7;g=(65535&g)>>>3;f[9]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[10]=g&7;g=(65535&g)>>>3;f[11]=g&7;f[12]=(65535&g)>>>3&7;g=a[k++]&255;e[1]=g&127;g=(65535&g)>>>7|a[k++]<<1&511;i[1]=g&3;g=(65535&g)>>>2;j[1]=g&3;g=(65535&g)>>>2|a[k++]<<5&8191;h[1]=g&63;g=(65535&g)>>>6;f[13]=g&7;g=(65535&g)>>>3;f[14]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[15]=g&7;g=(65535&g)>>>3;f[16]=g&7;f[17]=(65535&g)>>>3&7;g=a[k++]&255;f[18]=
g&7;g=(65535&g)>>>3;f[19]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[20]=g&7;g=(65535&g)>>>3;f[21]=g&7;g=(65535&g)>>>3;f[22]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[23]=g&7;g=(65535&g)>>>3;f[24]=g&7;f[25]=(65535&g)>>>3&7;g=a[k++]&255;e[2]=g&127;g=(65535&g)>>>7|a[k++]<<1&511;i[2]=g&3;g=(65535&g)>>>2;j[2]=g&3;g=(65535&g)>>>2|a[k++]<<5&8191;h[2]=g&63;g=(65535&g)>>>6;f[26]=g&7;g=(65535&g)>>>3;f[27]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[28]=g&7;g=(65535&g)>>>3;f[29]=g&7;f[30]=(65535&g)>>>3&7;g=a[k++]&255;f[31]=g&
7;g=(65535&g)>>>3;f[32]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[33]=g&7;g=(65535&g)>>>3;f[34]=g&7;g=(65535&g)>>>3;f[35]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[36]=g&7;g=(65535&g)>>>3;f[37]=g&7;f[38]=(65535&g)>>>3&7;g=a[k++]&255;e[3]=g&127;g=(65535&g)>>>7|a[k++]<<1&511;i[3]=g&3;g=(65535&g)>>>2;j[3]=g&3;g=(65535&g)>>>2|a[k++]<<5&8191;h[3]=g&63;g=(65535&g)>>>6;f[39]=g&7;g=(65535&g)>>>3;f[40]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[41]=g&7;g=(65535&g)>>>3;f[42]=g&7;f[43]=(65535&g)>>>3&7;g=a[k++]&255;f[44]=g&7;
g=(65535&g)>>>3;f[45]=g&7;g=(65535&g)>>>3|a[k++]<<2&1023;f[46]=g&7;g=(65535&g)>>>3;f[47]=g&7;g=(65535&g)>>>3;f[48]=g&7;g=(65535&g)>>>3|a[k++]<<1&511;f[49]=g&7;g=(65535&g)>>>3;f[50]=g&7;f[51]=(65535&g)>>>3&7;c(d,e,j,i,h,f,q,160);return q}function c(a,b,c,q,y,r,u,z){var Tc=0,g=Array(160);g.fill(0);var A=Array(40);A.fill(0);for(var B=0;3>=B;B++,Tc+=13){var t=y[B],D=c[B],J=Tc,x=r,C=A,H=Array(13);H.fill(0);var F=void 0,E=F=0;15<t&&(F=(t>>3)-1);E=t-(F<<3);if(0==E)F=-4,E=7;else{for(;7>=E;)E=E<<1|1,F--;E-=
8}if(-4>F||6<F)throw"Invalid quantization, exp:"+F;if(0>E||7<E)throw"Invalid quantization, mant = "+E;t=Array(2);t[0]=F;t[1]=E;for(var F=t,t=H,G=void 0,L=E=void 0,N=void 0,E=i[F[1]],L=f(6,F[0]),F=f(L,1),N=16<=F?0:-16>=F?-0.0:0>F?j(1,-F):1<<F,O=F=0;13>O;O++){G=(x[J++]<<1)-7;if(!(7>=G&&-7<=G))throw"Invalid inverse quantization, temp = "+G;G<<=12;G=k(E,G);G=n(G,N);t[F++]=j(G,L)}x=13;F=t=0;if(!(0<=D&&3>=D))throw"Invalid positioning: Mc = "+D;switch(D){case 3:C[F++]=0;case 2:C[F++]=0;case 1:C[F++]=0;case 0:C[F++]=
H[t++],x--}do C[F++]=0,C[F++]=0,C[F++]=H[t++];while(0<--x);for(;4>++D;)C[F++]=0;t=b[B];F=q[B];C=A;x=D=H=void 0;fa=x=40>t||120<t?fa:t;if(!(40<=x&&120>=x))throw"Invlaid filtering Nr = "+x;H=l[F];if(-32768==H)throw"Invlaid filtering brp = "+H;for(t=0;39>=t;t++)D=k(H,m[t-x+120]),m[t+120]=n(C[t],D);hi5.tool.arraycopy(m,40,m,0,120);hi5.tool.arraycopy(m,120,g,40*B,39)}b=Array(8);c=o[p];q=o[p^=1];y=0;d(a,c,y++,0,0,-32,13107);d(a,c,y++,0,0,-32,13107);d(a,c,y++,0,2048,-16,13107);d(a,c,y++,0,-2560,-16,13107);
d(a,c,y++,0,94,-8,19223);d(a,c,y++,0,-1792,-8,17476);d(a,c,y++,0,-341,-4,31454);d(a,c,y++,0,-1144,-4,29708);for(a=0;8>a;a++)b[a]=n(q[a]>>2,c[a]>>2),b[a]=n(b[a],q[a]>>1);h(b);e(b,13,g,u,0,z);for(a=0;8>a;a++)b[a]=n(q[a]>>1,c[a]>>1);h(b);e(b,14,g,u,13,z);for(a=0;8>a;a++)b[a]=n(q[a]>>2,c[a]>>2),b[a]=n(b[a],c[a]>>1);h(b);e(b,13,g,u,27,z);for(a=0;8>a;a++)b[a]=c[a];h(b);e(b,120,g,u,40,z);a=z;for(b=z+160;b-- >z;a++)g=k(v,28180),v=n(u[a],g),u[a]=n(v,v)&65528}function d(a,b,d,c,e,j,i){c=n(a[d],j)<<10;c=f(c,
e<<1);c=k(i,c);b[d]=n(c,c)}function h(a){for(var b=0,d=0;8>d;d++)0>a[d]?(b=-32768===a[d]?32767:-a[d],a[d]=-(11059>b?b<<1:20070>b?b+11059:n(b>>2,26112))):(b=a[d],a[d]=11059>b?b<<1:20070>b?b+11059:n(b>>2,26112))}function e(a,b,d,c,e,j){for(var i=0,h=0,k=0;0!=b;){b--;for(var i=d[e],g=7;0<=g;g--)h=a[g],k=y[g],k=(-32768==h&&-32768==k?32767:65535&h*k+16384>>15).toShort(),i=f(i,k),h=(-32768==h&&-32768==i?32767:65535&h*i+16384>>15).toShort(),y[g+1]=n(y[g],h);c[j+e++]=y[0]=i}}function k(a,b){return-32768==
a&&-32768==b?32767:(a*b+16384>>15).toShort()}function n(a,b){var d=a+b;return-32768>d?-32768:32767<d?32767:d}function f(a,b){var d=a-b;return-32768>d?-32768:32767<d?32767:d}function j(a,b){return 16<=b?0>a?-1:0:-16>=b?0:0>b?a<<-b:a>>b}var i=[18431,20479,22527,24575,26623,28671,30719,32767],l=[3277,11469,21299,32767],m=Array(280),o=[Array(8),Array(8)],p=0,fa=40,y=Array(9),v=0,r=Array(640),q=Array(320);this.decode=function(d,c,f){for(var e=[];c<f;)var j=b(d,c),e=e.concat(a(j)),c=c+65;return e};this.decodeBytes=
b}function C(a,b){function c(a,b,c,e,i){for(var a=a.createImageData(e,i),h=a.data,m=d,e=b+e,i=c+i,o,p=0,fa,y=c;y<i;y++)for(fa=b;fa<e;fa++)c=m[y][fa],o=p<<2,h[o]=c>>16&255,h[o+1]=c>>8&255,h[o+2]=c&255,h[o+3]=255,p++;return a}for(var d=Array(b),h=0;h<b;h++)d[h]=Array(a);var e=null;this.width=a;this.height=b;this.getBuffer=function(){return d};this.setRGB=function(a,b,c){d[b][a]=c};this.getRGB=function(a,b){return d[b][a]};this.setRGBs=function(a,b,c,e,i,h,m){for(var o=0,c=a+c,e=b+e,p=d;b<e;b++,h+=m)for(var o=
h,fa=a;fa<c;fa++)p[b][fa]=i[o++]};this.copyArea=function(a,b,c,e,i,h){for(var m=this.getRGBs(a,b,c,e),a=a+i,h=b+h,b=d,c=a+c,e=h+e,i=0,o=h;o<e;o++)for(h=a;h<c;h++)b[o][h]=m[i++]};this.getRGBs=function(a,b,c,e){for(var h=Array(c*e),l=d,c=a+c,e=b+e,m=0,o=b;o<e;o++)for(b=a;b<c;b++)h[m++]=l[o][b];return h};this.repaint=function(a,b,d,e){Ra.putImageData(c(Ra,a,b,d,e),a,b)};this.postPaint=function(a,b,d,c){e?e.union(a,b,d,c):e=new hi5.graphic.Rectangle(a,b,d,c)};this.commitPaint=function(){e&&(this.repaint(e.x,
e.y,e.width,e.height),e=null)};this.fillRect=function(a,b,c,e,h){for(var l=d,c=a+c,e=b+e,m=b;m<e;m++)for(b=a;b<c;b++)l[m][b]=h}}function ib(){if(!U&&"sessionStorage"in window){var a=sessionStorage["SI_"+r.server];if(null!=a)try{var b=JSON.parse(a);if(!("random"in b))return"";for(var c=b.random,a=0;16>a;a++)c[a]&=255;1<svGlobal.log&&console.log("load session, id="+b.logId+" server="+r.server);return"&logId="+b.logId+"&random="+encodeURIComponent(la.enc(c))}catch(d){}}return""}function qc(a){return 4278190080|
(a>>8&248|a>>13&7)<<16|(a>>3&252|a>>9&3)<<8|a<<3&248|a>>2&7}function Uc(a){return 4278190080|(a>>7&248|a>>12&7)<<16|(a>>2&248|a>>8&7)<<8|a<<3&248|a>>2&7}function Vc(a){return 4278190080|ga[0][a]<<16|ga[1][a]<<8|ga[2][a]}function Wc(a){return 4278190080|(a&255)<<16|a&65280|(a&16711680)>>16}function Xc(a){return 4278190080|(a&255)<<16|a&65280|(a&16711680)>>16}function Rb(a){p=a;Yc=(a+7)/8>>0;switch(a){case 16:oa=qc;break;case 15:oa=Uc;break;case 8:oa=Vc;break;case 32:oa=Wc;break;case 24:oa=Xc}}function Sb(a,
b){o=a;u=b;N=O=0;H=o-1;E=u-1}function rc(a){var b=__svi18n.errorCode[a];if(b){if(r.onerror)r.onerror({name:a,message:b});r.displayMsg&&hi5.notifications.notify({msg:b});0<svGlobal.log&&console.error(b)}}function Zc(){Aa=null;L=!1;ga=null;zd();X=new Tb;Sa=0;sc=null;Ub=Array(256);jb=[];for(var a=0;12>a;a++)tc[a]=Array(256);kb=Array(20);Ta.reset()}function $c(){var a;if(null==Ba)a="";else{a=lb()+"/CLIP?s="+Ba+"&t="+(new Date).getTime();var b=new XMLHttpRequest;b.open("GET",a,!1);b.setRequestHeader("Content-Type",
"text/plain;charset=UTF-8");b.send(null);a=b.responseText}return a}function ad(){function a(a){return a.winWidth&&a.winHeight&&a.showState}var b=[],c=this;this.addWin=function(a){b.push(a)};this.getAll=function(){return b};this.hasWin=function(a){return 0<=b.indexOf(a)};this.close=function(){for(var a=0,c=b.length;a<c;a++)b[a].close()};this.delWin=function(a){for(var c=0,e=b.length;c<e;c++)if(b[c].id==a)return b.splice(c,1),c;return-1};this.isRunning=function(){var d,c=b.length;if(1>c)return!1;for(var e=
0,c=b.length;e<c;e++)if(d=b[e],1>d.ownerWinid||a(d))return!0;return!1};this.getWinById=function(a){var c,e=b.length;if(1>e)return!1;for(var k=0,e=b.length;k<e;k++)if(c=b[k],c.id==a)return c;return null};this.getTopWin=function(d){var h=null,e,k=d.length;for(e=0;e<k&&(!(h=c.getWinById(d[e]))||!a(h));e++)h=null;if(!h){console.log("No win found");k=b.length;for(e=k-1;0<=e&&!(h=b[e],a(h));e--)h=null}return h};this.getMain=function(b){if(b=c.getTopWin(b)){for(var h;0<b.ownerWinid;)if((h=c.getWinById(b.ownerWinid))&&
a(h))b=h;else break;return b}return null}}function Vb(a,b){L&&(1<svGlobal.log&&console.log("reconnecting..."),t.send("8E0"+(a&-4)+"\t"+(b&-4)))}function Wb(a){var b={},c=0;this.read=function(d,h,e){var k=z.getFocused().fileProgress,n=b[d];if("undefined"!=typeof n){var f=n.name;1>n.size?alert(__svi18n.file.zero+f):(n=n.slice(h,h+e),f=new FileReader,f.onloadend=function(b){b.target.readyState==FileReader.DONE&&(b=new Uint8Array(b.target.result),a.send(d,h,e,b),c+=e,k.setProgress(c))},f.readAsArrayBuffer(n))}};
this.addFile=function(d){if(!("slice"in d)&&(d.slice=d.webkitSlice||d.mozSlice,!("slice"in d))){alert(__svi18n.file.slice);return}var c=z.getFocused().fileProgress;"none"==c.style.display&&(c.style.display="block");var e=d.name;b[e]=d;c.maxValue+=d.size;a.start(e,d.size)};this.confirmId=function(a,c){b[a]=b[c]};this.close=function(a){var h=z.getFocused(),e=h.fileProgress,k=b[a];k&&(delete b[a],delete b[k.name]);for(var n in b)return;c=e.maxValue=0;e.style.display="none";h.showMessage(__svi18n.file.uploadDone);
h.refreshFiles()}}function uc(a){if(ha&&Ca)for(var b=0,c=a.length;b<c;b++)ha.addFile(a[b])}function vc(){this.start=function(a,b){t.send("3A0"+a+"\t"+b)};this.send=function(a,b,c,d){t.send("3A3"+a+"\t"+b+"\t"+c+"\t"+la.enc(d))}}function Eb(a,b){return B&&B.width>a&&B.height>b?B:new C(a,b)}function Md(a){0<svGlobal.log&&console.log(a)}function Nd(){1<svGlobal.log&&console.log("opened...");L=!0;z.setConnected(!0);t.send("87"+navigator.userAgent);if(r.onopen)r.onopen()}function Fb(a){a=la.dec(a,0);return new RdpBuffer(a,
0,a.length)}function Od(a){var b,c=a.data;if("string"==typeof c)switch(b=parseInt(c.substring(0,2),16),a=c.substring(2),b){case 15:if(Z&&Z.onopen)Z.onopen();break;case 26:b=JSON.parse(a);if(b.name){1<svGlobal.log&&console.log("msg="+a);if(r.onerror)r.onerror(b);a=__svi18n.errorCode["S"+b.name];a+=b.message;r.displayMsg&&r.showMessage(a)}else 0<svGlobal.log&&console.erro("No error code for message:"+a);break;case 27:z.drawLicense(a);break;case 48:Xb(Fb(a));break;case 49:Yb(Fb(a));break;case 50:b=parseInt(a.substring(0,
1));a=a.substring(1);switch(b){case 1:1<svGlobal.log&&console.log("....... copy to clip:"+a);z.copyToClip(a);if(r.openLink&&(b=0==a.indexOf("http://")||0==a.indexOf("https://")||0==a.indexOf("ftp://")||0==a.indexOf("mailto:")||0==a.indexOf("tel:")||0==a.indexOf("callto:"),!b&&0==a.indexOf("www.")&&(b=!0,a="http://"+a),b))(b=z.getFocused())&&b.processLink(a);break;case 2:1<svGlobal.log&&console.log("....... clipReq, clipString:"+Aa),Da.clipRequired=!0,Da.prePaste||(t.send("881"+(null==Aa?"":Aa)),Da.clipRequired=
!1,Aa="")}break;case 51:z.setReadOnly("1"==a);break;case 54:a=lb()+a;1<svGlobal.log&&console.log("Downloading file:"+a);b=z.getFocused();null!=b&&b.showPDF(a);break;case 55:b=parseInt(a.substring(0,1),16);a=a.substring(1);switch(b){case 0:a=a.split("\t");D=parseInt(a[0]);v=parseInt(a[1]);x=parseInt(a[2]);J=parseInt(a[3]);1<svGlobal.log&&console.log("Audio Format, tag="+D+" channels="+v+" bitsPerSample="+x+" samplePerSec="+J);hi5.browser.isFirefox&&null==pa&&(pa=new Zb(r.audioBuffer));break;case 1:Pd(a)}break;
case 56:Ua=a=JSON.parse(a);Ba=a.session;Ua.server=r.server;if(a=hi5.$("joinSelect"))a.value=Ua.joinMode;if(a=hi5.$("requestControl"))a.disabled=Ua.hasControl;break;case 58:b=a;a=parseInt(b.charAt(0));b=b.substring(1);if(5==a)Da.notifyFiles(JSON.parse(b));else if(null!=ha)switch(b=b.split("\t"),a){case 1:ha.confirmId(b[0],b[1]);break;case 2:ha.read(b[0],parseInt(b[1]),parseInt(b[2]));break;case 4:ha.close(b[0])}break;case 59:a=la.dec(a,0);a=(new RdpBuffer(a,0,a.length)).getLittleEndian32();Va||!(a&
16)?(Gb=!1,ha=null,z.execute("setFileHandler",[null])):a&128&&(ha=null,z.execute("disableUpload",[null]));if(a&64&&(b=__svi18n.info.recording))r.displayMsg&&hi5.notifications.notify({msg:b}),1<svGlobal.log&&console.log(b);a&256||z.execute("disableShadow",[null]);break;case 60:$b(Fb(a));break;case 61:b=JSON.parse(a);switch(b.type){case 0:Sb(b.width,b.height);B=Eb(o,u);Rb(b.color);if(a=b.server)r.server=b.server;ac=b.length;if(c=z.getFocused())if(c.setSize(o,u,U?"hidden":null),a&&r.setTitle&&(c.browser.document.title=
r.server),a=b.keyboard,"undefined"!==typeof a&&0===a&&c.setUnicode(!0),a=b.mapDisk)Gb=!0,c.setFileHandler(uc),null==ha&&(ha=new Wb(new vc));if(r.onopened)r.onopened(b);break;case 1:if(a=b.duration,r.onprogress)r.onprogress(a,ac)}break;case 62:Qd(a);break;case 63:a=Fb(a);Z&&Z.process(a);break;default:1<svGlobal.log&&console.log("@TODO:"+c+"\n")}else switch(a=new Int8Array(c),a=new RdpBuffer(a,0,a.length),b=a.getLittleEndian16(),b){case 48:Xb(a);break;case 49:Yb(a);break;case 55:switch(a.getByte()){case 0:D=
a.getLittleEndian16();v=a.getLittleEndian16();J=a.getLittleEndian32();a.skipPosition(6);x=a.getLittleEndian16();1<svGlobal.log&&console.log("Audio Format, tag="+D+" channels="+v+" bitsPerSample="+x+" samplePerSec="+J);hi5.browser.isFirefox&&null==pa&&(pa=new Zb(r.audioBuffer));break;case 1:Rd(a)}break;case 60:$b(a);break;case 63:Z&&Z.process(a);break;default:1<svGlobal.log&&console.log("@TODO:"+b+"\n")}}function Qd(a){var b=parseInt(a.substring(0,1),16),c,d=a.substring(1),a=!1;switch(b){case 0:c=
JSON.parse(d);Zc();L=!0;b=c.width;a=c.height;if(b==o&&a==u)break;Sb(b,a);for(var d=0,h=z.length;d<h;d++)z[d].setSize(b,a,U?"hidden":null);B=Eb(b,a);break;case 1:r.reconnectOnResize=!1;c=JSON.parse(d);r.onsessionjoin&&(a=r.onsessionjoin(c));if(a)break;r.showMessage(__svi18n.info.joinsession.applyArgs([c.numericId,c.__ip,c.name]));break;case 2:c=JSON.parse(d);r.onsessionexit&&(a=r.onsessionexit(c));if(a)break;r.showMessage(__svi18n.info.exitsession.applyArgs([c.numericId,c.__ip,c.name]));break;case 3:z.setReadOnly(!1);
if(b=hi5.$("requestControl"))b.disabled=!0;r.ongivecontrol&&(a=r.ongivecontrol());if(a)break;r.showMessage(__svi18n.info.givecontrol);break;case 4:z.setReadOnly(!0);if(b=hi5.$("requestControl"))b.disabled=!1;r.ontakebackcontrol&&(a=r.ontakebackcontrol());if(a)break;r.showMessage(__svi18n.info.nocontrol);break;case 5:c=JSON.parse(d);r.onrequirecontrol&&(a=r.onrequirecontrol(c));if(a)break;b=__svi18n.info.title.applyArgs([c.name,c.numericId,c.__ip]);hi5.notifications.notify({title:b,msg:"Requesting control.",
cbYes:function(){r.giveControl(c.numericId);this.destroy()},cbNo:function(){r.refuseControl(c.numericId);this.destroy()}})}}function $b(a){switch(a.getByte()){case 32:a.getLittleEndian16();var b=a.getLittleEndian16(),a=a.getLittleEndian16();z.getFocused().moveCursor(b,a,!0)}}function Pd(a){function b(a){var b=0,a=a*k;for(f=0;f<k;f++)b|=(e[a+f]&255)<<8*f;b>j?(b-=l,b/=-i):b/=j;return b}function c(){t.send("8A"+h)}if(ca.available){var d=a.indexOf("\t"),h=a.substring(0,d),e=la.dec(a,d+1),a=x,k=a>>3,n=
Math.floor(e.length/k),f=0,j=Math.pow(2,a-1)-1,i=-j-1,l=Math.pow(2,a),a=0;if(hi5.browser.isFirefox){d=Array(n);for(a=0;a<n;a++)d[a]=b(a);a=pa.add(d);setTimeout(c,a-1E3*ca.delay)}else{for(var d=v,n=Math.floor(n/d),m=ca.getBuffer(n),o=m.getChannelData(0),p=m.getChannelData(1),a=0;a<n;){var fa=2*a,y=b(fa);1==d?(y*=0.707,o[a]=y,p[a]=y):(o[a]=y,p[a]=b(fa+1));a++}a=ca.playBuffer(m);setTimeout(c,1E3*(a-ca.delay))}}}function Rd(a){function b(){var a=0,a=e[i++]&255|(e[i++]&255)<<8;a>n?(a-=j,a/=-f):a/=n;return a}
function c(){t.send("8A"+d)}if(ca.available){var d=a.getByte()+","+a.getLittleEndian16()+","+a.getLittleEndian64(),h=a.getPosition(),e=a.getData(),k=a.getEnd()-h;49==D&&(Hb||(Hb=new ea),e=Hb.decode(e,h,k),h=0,k=e.length);var a=x,k=Math.floor(k/(a>>3)),n=Math.pow(2,a-1)-1,f=-n-1,j=Math.pow(2,a),i=h,h=0;if(hi5.browser.isFirefox){a=Array(k);for(h=0;h<k;h++)a[h]=b(h);h=pa.add(a);setTimeout(c,h-1E3*ca.delay)}else{for(var a=v,k=Math.floor(k/a),l=ca.getBuffer(k),m=l.getChannelData(0),o=l.getChannelData(1),
h=0;h<k;){var p=b();1==a?(p*=0.707,m[h]=p,o[h]=p):(m[h]=p,o[h]=b());h++}h=ca.playBuffer(l);Va||setTimeout(c,1E3*(h-ca.delay))}}}function Zb(a){var b=[],c,d,h,e=new Sd(v,J,function(b){var c=b.length,e=c>k.size();if(d||e)k.stop(),setTimeout(function(){k.start()},1E3*a);else for(e=0;e<c;e++)b[e]=k.pull()}),k=this;this.delay=a;this.reset=function(){c=b.length=0;d=!0;e.stop();h=0};this.reset();this.start=function(){d&&(e.start(),d=!1)};this.stop=function(){e.stop();d=!0};this.size=function(){for(var a=
b.length,c=0,d=0;d<a;d++)c+=b[d].length;return c};this.add=function(c){var d=(new Date).getTime();h<d&&(h=d);h+=1E3*(c.length/(J*v));var j=b.length;b[j]=c;0==j&&(d=(new Date).getTime(),setTimeout(function(){e.start()},1E3*a));return h-d};this.pull=function(){if(0==b.length)return null;var a=b[0];if(c<a.length)return a[c++];b.shift();c=0;return this.pull()}}function Sd(a,b,c){function d(){var a;if(n){a=h.mozWriteAudio(n.subarray(f));e+=a;f+=a;if(f<n.length)return;n=null}a=h.mozCurrentSampleOffset()+
k-e;if(0<a){var b=new Float32Array(a);c(b);a=h.mozWriteAudio(b);a<b.length&&(n=b,f=a);e+=a}}var h=new Audio;h.mozSetup(a,b);var e=0,k=a*b/2,n=null,f=0,j=null;this.start=function(){j=setInterval(d,100)};this.stop=function(){null!=j&&clearInterval(j)}}function lb(){var a=m.indexOf("://"),b=m.substring(a+3),a=b.indexOf("/");0<a&&(b=b.substring(0,a));return location.protocol+"//"+b}function Xb(a){var b=a.getLittleEndian16(),c=a.getByte(),d=a.getByte(),h=a.getLittleEndian16(),e=null;if(0!=(d&32)){if(65536<
b)throw"Invalid package size for decompression.";if(-1==Ta.dec(a.getData(),a.getPosition(),h-18,d))throw"Error on decompressing data.";e=Ta.getData()}else e=a;switch(c){case 2:a=e;b=a.getLittleEndian16();switch(b){case 0:a.skipPosition(2);b=a.getLittleEndian16();a.skipPosition(2);bc(a,b);break;case 1:cc(a);break;case 2:dc(a);break;case 3:break;default:1<svGlobal.log&&console.log("Warn: Unimplemented Update type "+b)}break;case 20:break;case 31:break;case 27:a=e;b=0;b=a.getLittleEndian16();a.skipPosition(2);
switch(b){case 3:a.skipPositon(4);break;case 6:mb(a,24);break;case 7:wc(a);break;case 1:a=a.getLittleEndian16();switch(a){case 0:z.setCursor("default");break;default:1<svGlobal.log&&console.log("XXX system pointer message "+a)}break;case 8:b=a.getLittleEndian16(),mb(a,b)}break;case 34:break;case 38:b=e;a=b.getLittleEndian32();if(3>a)Ca=!0;else if(3==a)if(Ca=!1,b.skipPosition(2),2==b.getLittleEndian32())r.displayMsg&&r.showMessage(__svi18n.logError);else{b.skipPosition(4);if(28!=b.getLittleEndian32())throw"Invalid length of SaveSessoinInfo PDU";
b.skipPosition(4);Ca=!0;a={};a.logId=b.getLittleEndian32();a.time=(new Date).getTime();b=b.getBytes(16);c=Array(16);for(d=0;16>d;d++)c[d]=b[d]&255;a.random=c;t.send("8D"+a.logId+"\t"+la.enc(c));if("sessionStorage"in window)try{sessionStorage["SI_"+r.server]=JSON.stringify(a)}catch(k){}}break;case 47:a=e.getLittleEndian32();1>a||rc(a);break;case 54:a=e.getLittleEndian32().toString(16).toUpperCase();a=__svi18n.serverStatus[a];r.displayMsg&&r.showMessage(a);break;default:1<svGlobal.log&&console.log("warn: Unimplemented Data PDU type "+
c)}}function Yb(a){var b=a.getByte(),c=b&15,d=b>>4&3;if(0!=d)throw"Fragmentation is not supported yet";var h,e=0;2==(b>>6&3)&&(e=a.getByte());h=a.getLittleEndian16();b=null;if(0!=(e&32)){if(1!=(e&15))throw"only support PACKET_COMPR_TYPE_64K";if(-1==Ta.dec(a.getData(),a.getPosition(),h,e))throw __svi18n.errorDecompress;b=Ta.getData()}else b=a;if(0!=d)if(2==d&&(null==Ea?Ea=[]:Ea.length=0),Ea.push(b.getData().slice(b.getPosition(),b.getEnd())),1==d){a=0;d=Ea.length;for(a=0;a<d;a++);e=[];for(a=0;a<d;a++)e.concat(Ea[a]);
b=new RdpBuffer(e,0,e.length);Ea.length=0}else return;switch(c){case 0:c=b.getLittleEndian16();bc(b,c);break;case 1:b.skipPosition(2);cc(b);break;case 2:b.skipPosition(2);dc(b);break;case 3:break;case 5:z.setCursor("default");break;case 6:break;case 8:break;case 9:mb(b,24);break;case 10:wc(b);break;case 11:c=b;a=c.getLittleEndian16();mb(c,a);break;default:1<svGlobal.log&&console.log("XXX RDP5 opcode "+c)}}function wc(a){a=a.getLittleEndian16();(a=ec(a))&&z.setCursor(a)}function Td(a,b,c,d,h,e,k,n){this.x=
a;this.y=b;this.width=c;this.height=d;this.mask=h;this.pixel=e;this.bpp=k;this.cache_idx=n}function mb(a,b){if(!Ud){var c=0,d=0,h=0,e=0,k=0,n=0,f=0,k=a.getLittleEndian16(),c=a.getLittleEndian16(),d=a.getLittleEndian16(),h=a.getLittleEndian16(),e=a.getLittleEndian16(),n=a.getLittleEndian16(),f=a.getLittleEndian16(),f=a.getBytes(f),j=a.getBytes(n);if(0>c||c>=h-1)c=0;0>d?d=0:d>=e&&(d=e-1);for(var i=!0,l=0;l<n;l++)if(-1!=j[l]){i=!1;break}if(!i){f=new Td(c,d,h,e,j,f,b,k);if(!hi5.browser.isOpera){var d=
f.x,h=f.y,n=f.width,e=f.height,c=f.cache_idx,j=f.mask,i=f.pixel,l=f.bpp,f=Array(n*e),m=0,o=0,p,r;for(p=0;p<e;p++)for(r=0;r<n;r++){o=p;1!=l&&(o=e-o-1);o=o*n+r;o=0==(j[o/8>>0]&128>>o%8)?1:0;f[m]=Vd(r,p,n,e,l,i);if(0==o&&0!=f[m])f[m]=~f[m],f[m]|=4278190080;else if(1==o||0!=f[m])f[m]|=4278190080;m++}i=4*n*e;l=n*e/8;j=62+i+l+l;j=new RdpBuffer(Array(j),0,j);j.setLittleEndian16(0);j.setLittleEndian16(2);j.setLittleEndian16(1);j.setByte(n);j.setByte(e);j.setByte(0);j.setByte(0);j.setLittleEndian16(d);j.setLittleEndian16(h);
j.setLittleEndian32(40+i+l+l);j.setLittleEndian32(22);j.setLittleEndian32(40);j.setLittleEndian32(n);j.setLittleEndian32(2*e);j.setLittleEndian16(1);j.setLittleEndian16(32);j.setLittleEndian32(0);j.setLittleEndian32(l+l);j.setLittleEndian32(0);j.setLittleEndian32(0);j.setLittleEndian32(0);j.setLittleEndian32(0);for(i=e-1;0<=i;i--)for(l=0;l<n;l++)m=f[n*i+l],j.setByte(m&255),j.setByte(m>>8&255),j.setByte(m>>16&255),j.setByte(m>>24&255);n=n/8>>0;for(i=0;i<e;i+=1)for(l=0;l<n;l+=1)j.setByte(0);for(i=0;i<
e;i+=1)for(l=0;l<n;l+=1)j.setByte(0);d={data:"data:image/x-icon;base64,"+la.enc(j.getData()),hotX:d,hotY:h};if(20>c)kb[c]=d;else throw"Could not put Cursor!";}(k=ec(k))&&z.setCursor(k)}}}function Vd(a,b,c,d,h,e){1!=h&&(b=d-b-1);b=(b*c+a)*h;c=b/8>>0;a=e[c]&255;switch(h){case 1:return 0==(a&128>>b%8)?0:4294967295;case 8:return 0==a?0:4294967295;case 15:return a|=(e[c+1]&255)<<8,h=Array(4),Ib(a,15,h,0),h[0]<<16|h[1]<<8|h[2];case 16:return a|=(e[c+1]&255)<<8,h=Array(4),Ib(a,16,h,0),h[0]<<16|h[1]<<8|h[2];
case 24:return(e[c+2]&255)<<16|(e[c+1]&255)<<8|a;case 32:return(e[c+3]&255)<<24|(e[c+2]&255)<<16|(e[c+1]&255)<<8|a;default:throw"invalid bpp value for Xor Mask.";}}function dc(a){var b=0,c=null,d=null,h=null,e=0;a.skipPosition(2);b=a.getLittleEndian16();a.skipPosition(2);for(var c=Array(b),d=Array(b),h=Array(b),a=a.getBytes(3*b),k=0;k<b;k++)c[k]=a[e],d[k]=a[e+1],h[k]=a[e+2],e+=3;256==b&&(null==ga&&(ga=Array(3)),ga[0]=c,ga[1]=d,ga[2]=h)}function bc(a,b){for(var c=0,d=0;c<b;){d=a.getByte();if(0==(d&
1)){var h=d>>2;if(2!=(d&3))throw"Not a valid Alt secondary order";switch(h){case 11:var e=a,k=e.getLittleEndian16(),n=e.getLittleEndian32(),f=e.getPosition()+(k-7);if(0!=(n&16777216)){var j=n,i=e,l=i.getLittleEndian32();0!=(j&1073741824)?1<svGlobal.log&&console.log("XXX rail icon, winId="+l):0!=(j&2147483648)?1<svGlobal.log&&console.log("XXX rail cache icon, winId="+l):0!=(j&536870912)?(1<svGlobal.log&&console.log("***** delete winId="+l),z.delWin(l)):Wd(i,j,l)}else if(0!=(n&33554432))1<svGlobal.log&&
console.log("XXX Alt Sec window Notify="+n);else if(0!=(n&67108864)){var m=n,r=e;1<svGlobal.log&&console.log("*** -- Alt Sec window Desktop="+m);if(0!=(m&1))1<svGlobal.log&&console.log("Desktop non monitored flags="+m);else if(0!=(m&32)){var v=r.getLittleEndian32();1<svGlobal.log&&console.log("Desktop monitored flags="+m+" winId="+v);if(0!=(m&16)){var t=r.getByte();if(0<t){var y=z.zOrders;y.length=t;for(var D=0;D<t;D++)y[D]=r.getLittleEndian32(),1<svGlobal.log&&console.log("---zorders:"+y[D])}}}}else 1<
svGlobal.log&&console.log("XXX Alt Sec window order flgas="+n);e.setPosition(f);break;default:1<svGlobal.log&&console.log("XXX Alt Sec order not implemented:"+h)}}else if(0!=(d&2)){var x=a,q=void 0,s=void 0,w=void 0,J=void 0,q=x.getLittleEndian16(),w=x.getLittleEndian16(),s=x.getByte(),J=x.getPosition()+q+7;switch(s){case 0:0<svGlobal.log&&console.log("TODO: raw bitmap cache");break;case 1:1<svGlobal.log&&console.log("TODO: color cache");break;case 2:var C=x,G=w,L=C.getByte();C.getByte();var P=C.getByte(),
U=C.getByte(),ea=C.getByte(),g=Math.floor((ea+7)/8),ga=C.getLittleEndian16(),ha=C.getLittleEndian16(),Z=0;0!=(G&1024)?Z=ga:(C.skipPosition(2),Z=C.getLittleEndian16(),C.skipPosition(2),C.skipPosition(2));var ca=void 0,la=C.getBytes(Z),ca=1==g?Ad(P,U,la.length,la):Bd(P,U,la.length,la,g,p),pa=L,Aa=ha,Ea=new Xd(ca,P,U,0,0,ea);"undefined"==typeof jb[pa]&&(jb[pa]=[]);jb[pa][Aa]=Ea;break;case 3:for(var F=x,Ra=null,Ca=0,Da=0,Pa=0,Ta=0,Ua=0,Ma=0,Na=0,hb=0,Ca=F.getByte(),Da=F.getByte(),ib=0;ib<Da;ib++){var Pa=
F.getLittleEndian16(),Ta=F.getLittleEndian16(),Ua=F.getLittleEndian16(),Ma=F.getLittleEndian16(),Na=F.getLittleEndian16(),hb=Na*Math.floor((Ma+7)/8)+3&-4,nb=Ra=new Yd(Ca,Pa,Ta,Ua,Ma,Na,F.getBytes(hb));if(12>nb.font&&256>nb.character)tc[nb.font][nb.character]=nb;else throw 0<svGlobal.log&&console.log("put font: font="+nb.font+" c="+nb.character),"Could not put font in cache";}break;case 4:1<svGlobal.log&&console.log("TODO: bmp cache 2");break;case 5:1<svGlobal.log&&console.log("TODO: bmp compressed cache2");
break;default:1<svGlobal.log&&console.log("XXX second Order, type="+s)}x.setPosition(J)}else{var ma=a,Wa=d,sa=0,Ba=0,ua=!1;if(0==(Wa&1))throw"Not a standard order!";0!=(Wa&8)&&(X.orderType=ma.getByte());switch(X.orderType){case 14:case 27:Ba=3;break;case 1:case 13:case 9:Ba=2;break;default:Ba=1}var Fb=ma,fc=Ba,Va=0,mb=0;0!=(Wa&64)&&fc--;0!=(Wa&128)&&(fc=2>fc?0:fc-2);for(var gb=0;gb<fc;gb++)mb=Fb.getByte(),Va|=mb<<8*gb;sa=Va;if(0!=(Wa&4)){if(0==(Wa&32)){var Fa=ma,$=X.bounds,Xa=Fa.getByte();0!=(Xa&
1)?$.left=A(Fa,$.left,!1):0!=(Xa&16)&&($.left=A(Fa,$.left,!0));0!=(Xa&2)?$.top=A(Fa,$.top,!1):0!=(Xa&32)&&($.top=A(Fa,$.top,!0));0!=(Xa&4)?$.right=A(Fa,$.right,!1):0!=(Xa&64)&&($.right=A(Fa,$.right,!0));0!=(Xa&8)?$.bottom=A(Fa,$.bottom,!1):0!=(Xa&128)&&($.bottom=A(Fa,$.bottom,!0))}var Oa=X.bounds;O=Oa.left;N=Oa.top;H=Oa.right;E=Oa.bottom}ua=0!=(Wa&16);switch(X.orderType){case 0:var gc=ma,ia=X.destBlt,hc=sa,Qa=ua;0!=(hc&1)&&(ia.x=A(gc,ia.x,Qa));0!=(hc&2)&&(ia.y=A(gc,ia.y,Qa));0!=(hc&4)&&(ia.cx=A(gc,
ia.cx,Qa));0!=(hc&8)&&(ia.cy=A(gc,ia.cy,Qa));0!=(hc&16)&&(ia.opcode=xc(gc.getByte()));var ob=ia.x,pb=ia.y,ic=ia.cx,jc=ia.cy,Rb=ia.opcode;if(!(ob>o||pb>u)){var kb=ob+ic-1;kb>H&&(kb=H);ob<O&&(ob=O);var ic=kb-ob+1,lb=pb+jc-1;lb>E&&(lb=E);pb<N&&(pb=N);jc=lb-pb+1;1>ic||1>jc||(yc(Rb,B,o,ob,pb,ic,jc,null,0,0,0),B.repaint(ob,pb,ic,jc))}break;case 1:var Ya=ma,Q=X.patBlt,Za=sa,zc=ua;0!=(Za&1)&&(Q.x=A(Ya,Q.x,zc));0!=(Za&2)&&(Q.y=A(Ya,Q.y,zc));0!=(Za&4)&&(Q.cx=A(Ya,Q.cx,zc));0!=(Za&8)&&(Q.cy=A(Ya,Q.cy,zc));if(0!=
(Za&16)){var Vb=Q,Eb=Ya.getByte();Vb.opcode=Eb&3|(Eb&48)>>2}0!=(Za&32)&&(Q.backgroundColor=Ga(Ya));0!=(Za&64)&&(Q.foregroundColor=Ga(Ya));Cd(Ya,Q.brush,Za>>7);var Gb=Q.x,Hb=Q.y;if(!(Gb>H||Hb>E)){var Ib=Q.opcode,$a=Gb,ab=Hb,qa=Q.cx,va=Q.cy,Ac=Q.foregroundColor,Db=Q.backgroundColor,pc=Q.brush.xOrigin,qc=Q.brush.yOrigin,Sb=Q.brush.style,rc=Q.brush.pattern,Ac=oa(Ac),Db=oa(Db),bd=$a+qa-1;bd>H&&(bd=H);$a<O&&($a=O);var qa=bd-$a+1,cd=ab+va-1;cd>E&&(cd=E);ab<N&&(ab=N);va=cd-ab+1;if(!(1>qa||1>va)){var qb=null;
switch(Sb){case 0:for(var qb=Array(qa*va),rb=0;rb<qb.length;rb++)qb[rb]=Ac;yc(Ib,B,o,$a,ab,qa,va,qb,qa,0,0);B.repaint($a,ab,qa,va);break;case 2:0<svGlobal.log&&console.log("hatch");break;case 3:for(var qb=Array(qa*va),Tb=0,rb=0;rb<va;rb++)for(var dd=0;dd<qa;dd++)qb[Tb]=0==(rc[(rb+qc)%8]&1<<(dd+pc)%8)?Ac:Db,Tb++;yc(Ib,B,o,$a,ab,qa,va,qb,qa,0,0);B.repaint($a,ab,qa,va);break;default:0<svGlobal.log&&console.log("Unsupported brush style "+Sb)}}}break;case 2:var sb=ma,S=X.screenBlt,tb=sa,Jb=ua;0!=(tb&1)&&
(S.x=A(sb,S.x,Jb));0!=(tb&2)&&(S.y=A(sb,S.y,Jb));0!=(tb&4)&&(S.cx=A(sb,S.cx,Jb));0!=(tb&8)&&(S.cy=A(sb,S.cy,Jb));0!=(tb&16)&&(S.opcode=xc(sb.getByte()));0!=(tb&32)&&(S.srcX=A(sb,S.srcX,Jb));0!=(tb&64)&&(S.srcY=A(sb,S.srcY,Jb));var Ha=S.x,Ia=S.y;if(!(Ha>H||Ia>E)){var bb=S.cx,Kb=S.cy,Wb=S.opcode,kc=S.srcX,lc=S.srcY,ed=Ha+bb-1;ed>H&&(ed=H);Ha<O&&(Ha=O);var bb=ed-Ha+1,fd=Ia+Kb-1;fd>E&&(fd=E);Ia<N&&(Ia=N);Kb=fd-Ia+1;kc+=Ha-S.x;lc+=Ia-S.y;1>bb||1>Kb||(12!=Wb?yc(Wb,B,bb,Ha,Ia,bb,Kb,null,bb,kc,lc):B.copyArea(kc,
lc,bb,Kb,Ha-kc,Ia-lc),B.repaint(Ha,Ia,bb,Kb))}break;case 9:var cb=ma,W=X.line,db=sa,Bc=ua;0!=(db&1)&&(W.mixmode=cb.getLittleEndian16());0!=(db&2)&&(W.startX=A(cb,W.startX,Bc));0!=(db&4)&&(W.startY=A(cb,W.startY,Bc));0!=(db&8)&&(W.endX=A(cb,W.endX,Bc));0!=(db&16)&&(W.endY=A(cb,W.endY,Bc));0!=(db&32)&&(W.backgroundColor=Ga(cb));0!=(db&64)&&(W.opcode=cb.getByte());var gd=cb,hd=W.pen,id=db>>7;0!=(id&1)&&(hd.style=gd.getByte());0!=(id&2)&&(hd.width=gd.getByte());0!=(id&4)&&(hd.color=Ga(gd));var ub=W.startX,
Ja=W.startY,vb=W.endX,mc=W.endY,uc=W.pen.color,vc=W.opcode-1;if(Ja==mc){if(ub>vb)var jd=ub,ub=vb,vb=jd;ub<O&&(ub=O);vb>H&&(vb=H)}else ub==vb&&(Ja>mc&&(jd=Ja,Ja=mc,mc=jd),Ja<N&&(Ja=N),Ja>E&&(Ja=E));Dd(ub,Ja,vb,mc,uc,vc);break;case 10:var wb=ma,ja=X.rectangle,xb=sa,Cc=ua;0!=(xb&1)&&(ja.x=A(wb,ja.x,Cc));0!=(xb&2)&&(ja.y=A(wb,ja.y,Cc));0!=(xb&4)&&(ja.cx=A(wb,ja.cx,Cc));0!=(xb&8)&&(ja.cy=A(wb,ja.cy,Cc));0!=(xb&16)&&(Sa=Sa&4294967040|wb.getByte());0!=(xb&32)&&(Sa=Sa&4294902015|wb.getByte()<<8);0!=(xb&64)&&
(Sa=Sa&4278255615|wb.getByte()<<16);ja.color=Sa;kd(ja.x,ja.y,ja.cx,ja.cy,ja.color,!0);break;case 11:var Lb=ma,ta=X.deskSave,Mb=sa,Dc=ua;0!=(Mb&1)&&(ta.offset=Lb.getLittleEndian32());0!=(Mb&2)&&(ta.left=A(Lb,ta.left,Dc));0!=(Mb&4)&&(ta.top=A(Lb,ta.top,Dc));0!=(Mb&8)&&(ta.right=A(Lb,ta.right,Dc));0!=(Mb&16)&&(ta.bottom=A(Lb,ta.bottom,Dc));0!=(Mb&32)&&(ta.action=Lb.getByte());var Ka=ta,ld=Ka.right-Ka.left+1,md=Ka.bottom-Ka.top+1;if(0==Ka.action)1>ld||1>md||(sc=B.getRGBs(Ka.left,Ka.top,ld,md));else{var nd=
ld,Xb=md,Yb=Ka.left,Zb=Ka.top;sc?(B.setRGBs(Yb,Zb,nd,Xb,sc,0,nd),B.repaint(Yb,Zb,nd,Xb)):0<svGlobal.log&&console.log("XXX no matched desktop save.")}break;case 13:var wa=ma,M=X.memBlt,La=sa,Nb=ua;0!=(La&1)&&(M.cacheID=wa.getByte(),M.colorTable=wa.getByte());0!=(La&2)&&(M.x=A(wa,M.x,Nb));0!=(La&4)&&(M.y=A(wa,M.y,Nb));0!=(La&8)&&(M.cx=A(wa,M.cx,Nb));0!=(La&16)&&(M.cy=A(wa,M.cy,Nb));0!=(La&32)&&(M.opcode=xc(wa.getByte()));0!=(La&64)&&(M.srcX=A(wa,M.srcX,Nb));0!=(La&128)&&(M.srcY=A(wa,M.srcY,Nb));0!=
(La&256)&&(M.cacheIDX=wa.getLittleEndian16());var Ec=M.x,Fc=M.y;if(!(Ec>H||Fc>E)){var Gc=M.cx,Hc=M.cy,nc="undefined"==typeof jb[M.cacheID]||"undefined"==typeof jb[M.cacheID][M.cacheIDX]?null:jb[M.cacheID][M.cacheIDX];if(null==nc)0<svGlobal.log&&console.log("Failed to get bitmap from cache, id:"+M.cacheID+" idx="+M.cacheIDX);else{var $b=nc.byteArray,ac=nc.width,bc=nc.bytesperpixel;1==bc?od($b,Ec,Fc,ac,nc.height,Gc,Hc,bc):1>Gc||1>Hc||(B.setRGBs(Ec,Fc,Gc,Hc,$b,0,ac),B.repaint(Ec,Fc,Gc,Hc))}}break;case 14:var ka=
ma,V=X.triBlt,na=sa,Ob=ua;0!=(na&1)&&(V.cacheID=ka.getByte(),V.colorTable=ka.getByte());0!=(na&2)&&(V.x=A(ka,V.x,Ob));0!=(na&4)&&(V.y=A(ka,V.y,Ob));0!=(na&8)&&(V.cx=A(ka,V.cx,Ob));0!=(na&16)&&(V.cy=A(ka,V.cy,Ob));0!=(na&32)&&(V.opcode=xc(ka.getByte()));0!=(na&64)&&(V.srcX=A(ka,V.srcX,Ob));0!=(na&128)&&(V.srcY=A(ka,V.srcY,Ob));0!=(na&256)&&(V.backgroundColor=Ga(ka));0!=(na&512)&&(V.foregroundColor=Ga(ka));Cd(ka,V.brush,na>>10);0!=(na&32768)&&(V.cacheIDX=ka.getLittleEndian16());0!=(na&65536)&&(V.unknown=
ka.getLittleEndian16());0<svGlobal.log&&console.log("XXX: TriBlt");break;case 22:var yb=ma,xa=X.polyLine,Pb=sa,cc=ua;0!=(Pb&1)&&(xa.x=A(yb,xa.x,cc));0!=(Pb&2)&&(xa.y=A(yb,xa.y,cc));0!=(Pb&4)&&(xa.opcode=yb.getByte());0!=(Pb&16)&&(xa.foregroundColor=Ga(yb));0!=(Pb&32)&&(xa.lines=yb.getByte());if(0!=(Pb&64)){var dc=yb.getByte();xa.dataSize=dc;xa.data=yb.getBytes(dc)}var zb=xa,Ic=zb.x,Jc=zb.y,wc=zb.foregroundColor,ec=zb.lines,Oc=zb.dataSize,pd=zb.data,Kc=Array(1);Kc[0]=Math.floor((ec-1)/4)+1;for(var eb=
0,Pc=0,Qc=zb.opcode-1,qd=0;qd<ec&&Kc[0]<Oc;qd++){var Rc=Ic,Sc=Jc;0==qd%4&&(eb=pd[Pc++]);0==(eb&192)&&(eb|=192);0!=(eb&64)&&(Ic+=Ed(pd,Kc));0!=(eb&128)&&(Jc+=Ed(pd,Kc));Dd(Rc,Sc,Ic,Jc,wc,Qc);eb<<=2}break;case 27:var R=ma,I=X.text2,T=sa;0!=(T&1)&&(I.font=R.getByte());0!=(T&2)&&(I.flags=R.getByte());0!=(T&4)&&(I.opcode=R.getByte());0!=(T&8)&&(I.mixmode=R.getByte());0!=(T&16)&&(I.foregroundColor=Ga(R));0!=(T&32)&&(I.backgroundColor=Ga(R));0!=(T&64)&&(I.clipLeft=R.getLittleEndian16());0!=(T&128)&&(I.clipTop=
R.getLittleEndian16());0!=(T&256)&&(I.clipRight=R.getLittleEndian16());0!=(T&512)&&(I.clipBottom=R.getLittleEndian16());0!=(T&1024)&&(I.boxLeft=R.getLittleEndian16());0!=(T&2048)&&(I.boxTop=R.getLittleEndian16());0!=(T&4096)&&(I.boxRight=R.getLittleEndian16());0!=(T&8192)&&(I.boxBottom=R.getLittleEndian16());0!=(T&16384)&&R.skipPosition(1);0!=(T&32768)&&R.skipPosition(1);0!=(T&65536)&&R.skipPosition(1);0!=(T&131072)&&R.skipPosition(1);0!=(T&262144)&&R.skipPosition(7);0!=(T&524288)&&(I.x=R.getLittleEndian16());
0!=(T&1048576)&&(I.y=R.getLittleEndian16());0!=(T&2097152)&&(I.length=R.getByte(),I.text=R.getBytes(I.length));var Fd=I.font,ya=I.flags,rd=I.mixmode,Gd=I.foregroundColor,Lc=I.backgroundColor,sd=I.clipLeft,td=I.clipTop,oc=I.boxLeft,ud=I.boxTop,aa=I.x,ra=I.y,Ab=I.length,da=I.text,vd=I.clipRight-sd,wd=I.clipBottom-td,Qb=I.boxRight-oc,xd=I.boxBottom-ud,ba=null,fb=0,Y=0;oc+Qb>o&&(Qb=o-oc);1<Qb?kd(oc,ud,Qb,xd,Lc,!1):1==rd&&kd(sd,td,vd,wd,Lc,!1);for(var Uc=da.length,K=0;K<Ab;)switch(da[Y+K]&255){case 255:var yd=
da[Y+K+2]&255;if(yd>Uc-Y){K=Ab=0;break}for(var Hd=Array(da[Y+K+2]&255),Vc=da,Wc=Y,Xc=Hd,Zc=yd,Mc=0;Mc<Zc;Mc++)Xc[0+Mc]=Vc[Wc+Mc];var $c=new Zd(yd,Hd),Id=da[Y+K+1]&255;if(Id<Ub.length)Ub[Id]=$c;else throw"Could not put Text in cache";K+=3;Ab-=K;Y=K;K=0;break;case 254:var Bb;a:{var Jd=da[Y+K+1]&255,Nc=null;if(Jd<Ub.length&&(Nc=Ub[Jd],null!=Nc&&null!=Nc.data)){Bb=Nc;break a}Bb=null}var Cb=null!=Bb?Bb.data:null;null!=Bb&&0==Cb[1]&&0==(ya&32)&&(0!=(ya&4)?ra+=da[Y+K+2]&255:aa+=da[Y+K+2]&255);K=K+2<Ab?K+
3:K+2;Ab-=K;Y=K;K=0;if(null==Bb)break;for(var ad=Bb.size,za=0;za<ad;za++)if(ba=Kd(Fd,Cb[za]&255),0==(ya&32)&&(fb=Cb[++za]&255,0!=(fb&128)?(0!=(ya&4)?ra+=Cb[za+1]&255|(Cb[za+2]&255)<<8:aa+=Cb[za+1]&255|(Cb[za+2]&255)<<8,za+=2):0!=(ya&4)?ra+=fb:aa+=fb),null!=ba)Ld(rd,aa+ba.offset&65535,ra+ba.baseLine&65535,ba.width,ba.height,ba.fontData,Lc,Gd,Yc,p),0!=(ya&32)&&(aa+=ba.width);break;default:ba=Kd(Fd,da[Y+K]&255),0==(ya&32)&&(fb=da[Y+ ++K]&255,0!=(fb&128)?(0!=(ya&4)?ra+=da[Y+K+1]&255|(da[Y+K+2]&255)<<
8:aa+=da[Y+K+1]&255|(da[Y+K+2]&255)<<8,K+=2):0!=(ya&4)?ra+=fb:aa+=fb),null!=ba&&(Ld(rd,aa+ba.offset&65535,ra+ba.baseLine&65535,ba.width,ba.height,ba.fontData,Lc,Gd,Yc,p),0!=(ya&32)&&(aa+=ba.width)),K++}1<Qb?0<xd&&B.postPaint(oc,ud,Qb,xd):0<vd&&0<wd&&B.postPaint(sd,td,vd,wd);break;default:1<svGlobal.log&&console.log("XXX Order type "+X.orderType)}0!=(Wa&4)&&zd()}c++}B.commitPaint()}function $d(a){this.id=a;this.fillBrowser=function(){var b=z.getOwnerSurface(this);null!=b?(b=b.browser,this.resize(0,
0,b.innerWidth,b.innerHeight)):0<svGlobal.log&&console.log("XXX No browser for "+a)};this.parent=function(){return z.getWinById(this.ownerWinid)};this.resize=function(a,c,d,h){t.send("8C1"+this.id+"\t"+a+"\t"+c+"\t"+d+"\t"+h)};this.checkBound=function(){var a=z.getOwnerSurface(this);if(null==a)console.log("no surface for checkBound");else{var a=a.browser,c=this.winWidth,d=this.winHeight,h=this.winOffsetX,e=this.winOffsetY;if(!(1>c||1>d))if(h>a.innerWidth||e>a.innerHeight)h>a.innerWidth&&(h=Math.floor(a.innerWidth/
2)),e>a.innerHeight&&(e=Math.floor(a.innerHeight/2)),this.resize(h,e,c,d)}};this.exeCommand=function(b){t.send("8C4"+a+"\t"+b)};this.activate=function(b){t.send("8C3"+a+"\t"+b)};this.close=function(){this.exeCommand(61536)}}function Oc(a,b,c){t.send("8C1"+a.id+"\t0\t0\t"+b+"\t"+c);a.winWidth=b;a.winHeight=c}function Wd(a,b,c){U||(U=!0);var d=0==(b&268435456);1<svGlobal.log&&console.log("\n\n================= winId="+c+" existed="+d);var h=d?z.getWinById(c):new $d(c);if(h){0!=(b&2)&&(h.ownerWinid=
a.getLittleEndian32(),1<svGlobal.log&&console.log("***** ownerWinid="+h.ownerWinid));0!=(b&8)&&(h.style=a.getLittleEndian32(),h.extStyle=a.getLittleEndian32(),1<svGlobal.log&&(console.log("***** winId="+c+" style="+h.style+" extStyle="+h.extStyle),console.log("*****--- WS_POPUP="+(0!=(h.style&2147483648))),console.log("*****--- WS_DLGFRAME="+(0!=(h.style&4194304))),console.log("*****--- DS_MODALFRAME="+(0!=(h.style&128))),console.log("*****--- WS_EX_DLGMODALFRAME="+(0!=(h.extStyle&1))),console.log("*****--- WS_EX_TOOLWINDOW="+
(0!=(h.extStyle&128))),console.log("*****--- WS_BORDER="+(0!=(h.style&8388608))),console.log("*****--- WS_CAPTION="+(0!=(h.style&12582912))),console.log("*****--- WS_OVERLAPPED="+(0!=(h.style&0))),console.log("*****--- WS_OVERLAPPEDWINDOW="+(0!=(h.style&13565952))),console.log("*****--- WS_POPUPWINDOW="+(0!=(h.style&2156396544))),console.log("*****--- WS_SIZEBOX="+(0!=(h.style&262144))),console.log("*****--- WS_CHILD="+(0!=(h.style&1073741824))),console.log("*****--- WS_EX_MDICHILD="+(0!=(h.extStyle&
64))),console.log("*****--- WS_EX_LAYERED="+(0!=(h.extStyle&524288)))));if(0!=(b&16)){h.showState=a.getByte();1<svGlobal.log&&console.log("***** winId="+c+" showState="+h.showState);var e=h.showState;if(3==e)h.fillBrowser();else switch(e){case 2:3==r.windowState&&setTimeout(function(){h.exeCommand(61728)},50);break;case 3:setTimeout(function(){h.fillBrowser()},50)}}0!=(b&4)&&(e=a.getLittleEndian16(),h.titleInfo=a.getUnicodeString(e,!1),1<svGlobal.log&&console.log("***** winId="+c+" title="+h.titleInfo));
0!=(b&16384)&&(h.clientOffsetX=a.getLittleEndian32(),h.clientOffsetY=a.getLittleEndian32(),1<svGlobal.log&&console.log("***** winId="+c+" coffX"+h.clientOffsetX+" coffY="+h.clientOffsetY));0!=(b&65536)&&(h.clientAreaWidth=a.getLittleEndian32(),h.clientAreaHeight=a.getLittleEndian32(),1<svGlobal.log&&console.log("***** winId="+c+" cw"+h.clientAreaWidth+" ch="+h.clientAreaHeight));0!=(b&131072)&&(h.rpContent=a.getLittleEndian32());0!=(b&262144)&&(h.rootParentHandle=a.getLittleEndian32());0!=(b&2048)&&
(h.winOffsetX=a.getLittleEndian32(),h.winOffsetY=a.getLittleEndian32(),1<svGlobal.log&&console.log("***** winId="+c+" offX"+h.winOffsetX+" offY="+h.winOffsetY));0!=(b&32768)&&(h.winClientDeltaX=a.getLittleEndian32(),h.winClientDeltaY=a.getLittleEndian32(),1<svGlobal.log&&console.log("***** winId="+c+" dX"+h.winClientDeltaX+" dY="+h.winClientDeltaY));0!=(b&1024)&&(h.winWidth=a.getLittleEndian32(),h.winHeight=a.getLittleEndian32(),1<svGlobal.log&&console.log("***** winId="+c+" w"+h.winWidth+" h="+h.winHeight));
0!=(b&256)&&(c=a.getLittleEndian16(),0<c&&a.skipPosition(8*c));0!=(b&4096)&&(h.visibleOffsetX=a.getLittleEndian32(),h.visibleOffsetY=a.getLittleEndian32());0!=(b&512)&&(b=a.getLittleEndian16(),h.numVisibilityRects=b,0<b&&a.skipPosition(8*b));d||z.addWin(h)}else console.log("XXX, No win with id:"+c)}function A(a,b,c){var d=0;c?(d=a.getByte(),127<d&&(d-=256),b+=d):b=a.getLittleEndian16();return b}function xc(a){return a&15}function Ga(a){var b=0,c=0,b=c=a.getByte(),c=a.getByte(),b=b|c<<8,c=a.getByte();
return b|c<<16}function Cd(a,b,c){0!=(c&1)&&(b.xOrigin=a.getByte());0!=(c&2)&&(b.yOrigin=a.getByte());0!=(c&4)&&(b.style=a.getByte());var d=b.pattern;0!=(c&8)&&(d[0]=a.getByte());if(0!=(c&16))for(c=1;8>c;c++)d[c]=a.getByte();b.pattern=d}function cc(a){var b=0,c=0,d=0,h=0,e=0,k=0,n=0,f=0,j=0,i=0,l=0,m=0,h=0,r,v,t,y;t=y=0;r=o;v=u;for(var b=a.getLittleEndian16(),z=0;z<b;z++){var c=a.getLittleEndian16(),d=a.getLittleEndian16(),h=a.getLittleEndian16(),e=a.getLittleEndian16(),k=a.getLittleEndian16(),n=
a.getLittleEndian16(),i=a.getLittleEndian16(),x=Math.floor((i+7)/8),l=a.getLittleEndian16(),m=a.getLittleEndian16(),f=h-c+1,j=e-d+1;r>c&&(r=c);v>d&&(v=d);t<h&&(t=h);y<e&&(y=e);p!=i&&(0<svGlobal.log&&console.log("Server limited colour depth to "+i+" bits"),Rb(i));if(0==l){h=k*x;e=n*h;i=Array(e);l=a.getPosition();for(m=0;m<n;m++){for(var q=a.getData(),s=l,w=i,D=(n-m-1)*h,A=h,C=0;C<A;C++)w[D+C]=q[s+C];l+=h}a.skipPosition(e);od(i,c,d,k,n,f,j,x)}else(0!=(l&1024)?h=m:(a.skipPosition(2),h=a.getLittleEndian16(),
a.skipPosition(4)),h=a.getBytes(h),1==x)?(h=Ad(k,n,h.length,h),od(h,c,d,k,n,f,j,x)):(x=Bd(k,n,h.length,h,x,p),1>f||1>j||(B.setRGBs(c,d,f,j,x,0,k),B.postPaint(c,d,f,j)))}B.commitPaint()}function zd(){O=0;H=o-1;N=0;E=u-1}function Dd(a,b,c,d,h,e){h=oa(h);if(a==c||b==d){var k,n,f;if(b==d){if(b>=N&&b<=E)if(c>a){if(a<O&&(a=O),c>H&&(c=H),k=b*o+a,f=c-a,!(1>f)){for(n=0;n<f;n++)Ma(e,B,a+n,b,h),k++;B.repaint(a,b,f+1,1)}}else if(c<O&&(c=O),a>H&&(a=H),k=b*o+a,f=a-c,!(1>f)){for(n=0;n<f;n++)Ma(e,B,c+n,b,h),k--;
B.repaint(c,b,f+1,1)}}else if(a>=O&&a<=H)if(d>b){if(b<N&&(b=N),d>E&&(d=E),k=b*o+a,f=d-b,!(1>f)){for(n=0;n<f;n++)Ma(e,B,a,b+n,h),k+=o;B.repaint(a,b,1,f+1)}}else if(d<N&&(d=N),b>E&&(b=E),k=b*o+a,f=b-d,!(1>f)){for(n=0;n<f;n++)Ma(e,B,a,d+n,h),k-=o;B.repaint(a,d,1,f+1)}}else{var j=Math.abs(c-a),i=Math.abs(d-b);k=a;n=b;var l,m,p,r,v,y;l=c>=a?f=1:f=-1;p=d>=b?m=1:m=-1;j>=i?(p=f=0,v=j,r=j/2,y=i):(m=l=0,v=i,r=i/2,y=j,j=i);if(!(1>j)){for(i=0;i<=j;i++)k<O||k>H||n<N||n>E||Ma(e,B,k,n,h),r+=y,r>=v&&(r-=v,k+=f,n+=
m),k+=l,n+=p;e=a<c?a:c;h=a>c?a:c;c=b<d?b:d;d=b>d?b:d;0>h-e||0>d-c||B.repaint(e,c,h-e+1,d-c+1)}}}function Ld(a,b,c,d,h,e,k,n,f){var j=0,i=128,j=Math.floor((d-1)/8)+1,l,n=oa(n),k=oa(k);3==f&&(n=(n&255)<<16|n&65280|(n&16711680)>>16,k=(k&255)<<16|k&65280|(k&16711680)>>16);if(!(b>H||c>E))if(f=b+d-1,f>H&&(f=H),d=b<O?O:b,f=f-b+1,l=c+h-1,l>E&&(l=E),h=c<N?N:c,l=l-h+1,!(1>f||1>l))if(j*=h-c,0==a)for(a=0;a<l;a++){for(var m=0;m<f;m++)0==i&&(j++,i=128),0!=(e[j]&i)&&b+m>=d&&0<d+m&&0<h+a&&B.setRGB(d+m,h+a,n),i>>=
1;j++;i=128;j==e.length&&(j=0)}else for(a=0;a<l;a++){for(m=0;m<f;m++)0==i&&(j++,i=128),b+m>=d&&0<b+m&&0<c+a&&(0!=(e[j]&i)?B.setRGB(b+m,c+a,n):B.setRGB(b+m,c+a,k)),i>>=1;j++;i=128;j==e.length&&(j=0)}}function Ed(a,b){var c=a[b[0]++]&255,d=c&128,c=0!=(c&64)?c|-64:c&63;0!=d&&(c=c<<8|a[b[0]++]&255);return c}function kd(a,b,c,d,h,e){if(!(a>H||b>E))if(c=a+c-1,c>H&&(c=H),a<O&&(a=O),c=c-a+1,d=b+d-1,d>E&&(d=E),b<N&&(b=N),d=d-b+1,!(1>c||1>d))if(B.fillRect(a,b,c,d,oa(h)),e)if(4E4<c*d){var e=Ra,k=Array(4);Ib(h,
p,k,0);e.fillStyle="rgba("+k[0]+","+k[1]+","+k[2]+","+k[3]+")";Ra.fillRect(a,b,c,d)}else B.postPaint(a,b,c,d)}function od(a,b,c,d,h,e,k,n){var h=a.length/n>>0,f=Array(h),j=oa;switch(n){case 1:for(var i=0;i<h;i++)f[i]=j(a[i]&255);break;case 2:for(i=0;i<h;i++)f[i]=j((a[2*i+1]&255)<<8|a[2*i]&255);break;default:for(i=0;i<h;i++)f[i]=j((a[i*n+2]&255)<<16)|(a[i*n+1]&255)<<8|a[i*n]&255}B.setRGBs(b,c,e,k,f,0,d);B.postPaint(b,c,e,k)}function Pc(){null!=t&&L&&(t.send("85"),t.close())}function Zd(a,b){this.size=
a;this.data=b}function Yd(a,b,c,d,h,e,k){this.font=a;this.character=b;this.offset=c;this.baseLine=d;this.width=h;this.height=e;this.fontData=k}function gb(a,b,c,d,h,e,k){for(var n=h*c+d,f=a.setRGB,j=a.getRGB,i=0;i<k;i++){for(var l=0;l<e;l++){if(null!=a){var m=j(d+l,h+i);f(d+l,h+i,~m&G)}else b[n]=~b[n]&G;n++}n+=c-e}}function yc(a,b,c,d,h,e,k,n,f,j,i){if(!(0>e|0>k|0>c|0>f))switch(a){case 0:n=b.setRGB;for(f=d;f<d+e;f++)for(b=h;b<h+k;b++)n(f,b,0);break;case 1:a=i*f+j;c=b.setRGB;for(j=0;j<k;j++){for(i=
0;i<e;i++)c(d+e,h+k,~(b.getRGB(d+e,h+k)|n[a])&G);a+=f-e}break;case 2:a=i*f+j;c=b.setRGB;b=b.getRGB;for(j=0;j<k;j++){for(i=0;i<e;i++){var l=b(d+e,h+k);c(d+e,h+k,l&~n[a]&G);a++}a+=f-e}break;case 3:gb(b,n,f,j,i,e,k);null==n?b.copyArea(j,i,e,k,d-j,h-i):b.setRGBs(d,h,e,k,n,0,f);break;case 4:gb(b,null,c,d,h,e,k);Qc(b,c,d,h,e,k,n,f,j,i);break;case 5:gb(b,null,c,d,h,e,k);break;case 6:a=i*f+j;c=b.setRGB;b=b.getRGB;for(j=0;j<k;j++){for(i=0;i<e;i++)l=b(d+i,h+j),c(d+i,h+j,l^n[a]&G),a++;a+=f-e}break;case 7:a=
i*f+j;c=b.setRGB;b=b.getRGB;for(j=0;j<k;j++){for(i=0;i<e;i++)l=b(d+i,h+j),c(d+i,h+j,~(l&n[a])&G),a++;a+=f-e}break;case 8:Qc(b,c,d,h,e,k,n,f,j,i);break;case 9:a=i*f+j;c=b.setRGB;b=b.getRGB;for(j=0;j<k;j++){for(i=0;i<e;i++)l=b(d+i,h+j),c(d+i,h+j,l^~n[a]&G),a++;a+=f-e}break;case 10:break;case 11:a=i*f+j;c=b.setRGB;b=b.getRGB;for(j=0;j<k;j++){for(i=0;i<e;i++)l=b(d+i,h+j),c(d+i,h+j,l|~n[a]&G),a++;a+=f-e}break;case 12:null==n?b.copyArea(j,i,e,k,d-j,h-i):b.setRGBs(d,h,e,k,n,0,f);break;case 13:gb(b,null,
c,d,h,e,k);Rc(b,c,d,h,e,k,n,f,j,i);break;case 14:Rc(b,c,d,h,e,k,n,f,j,i);break;case 15:n=b.setRGB;for(f=d;f<d+e;f++)for(b=h;b<h+k;b++)n(f,b,G);break;default:0<svGlobal.log&&console.log("unsupported opcode: "+a)}}function Ma(a,b,c,d,h){if(null!=b){var e=b.getRGB(c,d);switch(a){case 0:b.setRGB(c,d,0);break;case 1:b.setRGB(c,d,~(e|h)&G);break;case 2:b.setRGB(c,d,e&~h&G);break;case 3:b.setRGB(c,d,~h&G);break;case 4:b.setRGB(c,d,(~e&h)*G);break;case 5:b.setRGB(c,d,~e&G);break;case 6:b.setRGB(c,d,e^h&G);
break;case 7:b.setRGB(c,d,~e&h&G);break;case 8:b.setRGB(c,d,e&h&G);break;case 9:b.setRGB(c,d,e^~h&G);break;case 10:break;case 11:b.setRGB(c,d,e|~h&G);break;case 12:b.setRGB(c,d,h);break;case 13:b.setRGB(c,d,(~e|h)&G);break;case 14:b.setRGB(c,d,e|h&G);break;case 15:b.setRGB(c,d,G);break;default:0<svGlobal.log&&console.log("unsupported pixel opcode: "+a),b.setRGB(c,d,h)}}}function Qc(a,b,c,d,h,e,k,n,f,j){b=j*n+f;f=a.setRGB;a=a.getRGB;for(j=0;j<e;j++){for(var i=0;i<h;i++){var l=a(c+i,d+j);f(c+i,d+j,
l&k[b]&G);b++}b+=n-h}}function Rc(a,b,c,d,h,e,k,n,f,j){b=j*n+f;f=a.setRGB;a=a.getRGB;for(j=0;j<e;j++){for(var i=0;i<h;i++){var l=a(c+i,d+j);f(c+i,d+j,l|k[b]&G);b++}b+=n-h}}function Kd(a,b){if(12>a&&256>b){var c=tc[a][b];if(null!=c)return c}return null}function ec(a){return 20>a&&(a=kb[a],null!=a)?a:null}function Xd(a,b,c,d,h,e){this.byteArray=a;this.left=d;this.top=h;this.width=b;this.height=c;this.bitsperpixel=e;this.bytesperpixel=Math.floor((e+7)/8)}function Ib(a,b,c,d){switch(b){case 16:var b=
a>>8&248,h=a>>3&252,a=a<<3&255;c[d]=b|b>>5;c[d+1]=h|h>>6;c[d+2]=a|a>>5;c[d+3]=255;break;case 15:b=a>>7&248;h=a>>2&248;a=a<<3&255;c[d]=b|b>>5;c[d+1]=h|h>>5;c[d+2]=a|a>>5;c[d+3]=255;break;case 8:c[d]=ga[0][a];c[d+1]=ga[1][a];c[d+2]=ga[2][a];c[d+3]=255;break;case 32:c[d]=a&255,c[d+1]=a>>8&255,c[d+2]=a>>16&255,c[d+3]=a>>24&255;default:c[d]=a&255,c[d+1]=a>>8&255,c[d+2]=a>>16&255,c[d+3]=255}}function Na(a,b,c){for(var d=0,c=c-1;0<=c;c--)d<<=8,d|=a[b+c]&255;return d}function hb(a,b){var c=a[b]&255,d=(a[b+
1]&255)<<8|c,h=d>>7&248,d=d>>2&248,c=c<<3&255;return(h|h>>5)<<16|(d|d>>5)<<8|c|c>>5}function Sc(a,b,c){return a=0|a[b+c]&255}function Bd(a,b,c,d,h,e){switch(e){case 16:return ae(a,b,c,d);case 15:for(var h=b,e=b=-1,k=0,n=k+c,f=c=0,j=0,i=a,l=-1,m=0,o=f=0,p=0,r=j=0,y=4294967295,v=!1,t=!1,q=!1,s=Array(a*h);k<n;){m=0;f=d[k++]&255;c=f>>4;switch(c){case 12:case 13:case 14:c-=6;f&=15;j=16;break;case 15:c=f&15;9>c?(f=d[k++]&255,f|=(d[k++]&255)<<8):f=11>c?8:1;j=0;break;default:c>>=1,f&=31,j=32}0!=j&&(q=2==
c||7==c,0==f?f=q?(d[k++]&255)+1:(d[k++]&255)+j:q&&(f<<=3));switch(c){case 0:l==c&&!(i==a&&-1==b)&&(v=!0);break;case 8:o=hb(d,k),k+=2;case 3:p=hb(d,k);k+=2;break;case 6:case 7:y=hb(d,k);k+=2;c-=5;break;case 9:r=3;c=2;m=3;break;case 10:r=5,c=2,m=5}l=c;for(j=0;0<f;){if(i>=a){if(0>=h)throw"Decompressing bitmap failed! Height = "+h;i=0;h--;b=e;e=0+h*a}switch(c){case 0:v&&(s[e+i]=-1==b?y:s[b+i]^y,v=!1,f--,i++);if(-1==b){for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=0,f--,i++;for(;0<f&&i<a;)s[e+i]=0,f--,
i++}else{for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=s[b+i],f--,i++;for(;0<f&&i<a;)s[e+i]=s[b+i],f--,i++}break;case 1:if(-1==b){for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=y,f--,i++;for(;0<f&&i<a;)s[e+i]=y,f--,i++}else{for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=s[b+i]^y,f--,i++;for(;0<f&&i<a;)s[e+i]=s[b+i]^y,f--,i++}break;case 2:if(-1==b){for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)j<<=1,j&=255,0==j&&(r=0!=m?m&255:d[k++],j=1),s[e+i]=0!=(r&j)?y&255:0,f--,i++;for(;0<f&&i<a;)j<<=1,j&=255,0==j&&(r=
0!=m?m&255:d[k++],j=1),s[e+i]=0!=(r&j)?y:0,f--,i++}else{for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)j<<=1,j&=255,0==j&&(r=0!=m?m&255:d[k++],j=1),s[e+i]=0!=(r&j)?s[b+i]^y:s[b+i],f--,i++;for(;0<f&&i<a;)j<<=1,j&=255,0==j&&(r=0!=m?m&255:d[k++],j=1),s[e+i]=0!=(r&j)?s[b+i]^y:s[b+i],f--,i++}break;case 3:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=p,f--,i++;for(;0<f&&i<a;)s[e+i]=p,f--,i++;break;case 4:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=hb(d,k),k+=2,f--,i++;for(;0<f&&i<a;)s[e+i]=hb(d,k),k+=2,f--,i++;
break;case 8:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)t?(s[e+i]=p,t=!1):(s[e+i]=o,t=!0,f++),f--,i++;for(;0<f&&i<a;)t?(s[e+i]=p,t=!1):(s[e+i]=o,t=!0,f++),f--,i++;break;case 13:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=16777215,f--,i++;for(;0<f&&i<a;)s[e+i]=16777215,f--,i++;break;case 14:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=0,f--,i++;for(;0<f&&i<a;)s[e+i]=0,f--,i++;break;default:throw"Unimplemented decompress opcode "+c;}}}return s;case 32:if(16!=d[0])throw"Wrong tag.";input=1;h=Array(4*
a*b);e=Oa(d,input,a,b,h,3);input+=e;e=Oa(d,input,a,b,h,2);input+=e;e=Oa(d,input,a,b,h,1);input+=e;Oa(d,input,a,b,h,0);a=Math.floor(h.length/4);d=Array(a);for(e=b=0;e<a;e++)b=e<<2,d[e]=h[b+3]<<24|h[b+2]<<16|h[b+1]<<8|h[b+0]<<0;return d;default:for(var k=e=-1,n=0,c=n+c,q=j=i=0,l=a,m=-1,y=q=r=p=j=o=0,v=4294967295,w=s=t=!1,f=Array(a*b);n<c;){o=0;j=d[n++]&255;i=j>>4;switch(i){case 12:case 13:case 14:i-=6;j&=15;q=16;break;case 15:i=j&15;9>i?(j=d[n++]&255,j|=(d[n++]&255)<<8):j=11>i?8:1;q=0;break;default:i>>=
1,j&=31,q=32}0!=q&&(w=2==i||7==i,0==j?j=w?(d[n++]&255)+1:(d[n++]&255)+q:w&&(j<<=3));switch(i){case 0:m==i&&!(l==a&&-1==e)&&(t=!0);break;case 8:p=Na(d,n,h),n+=h;case 3:r=Na(d,n,h);n+=h;break;case 6:case 7:v=Na(d,n,h);n+=h;i-=5;break;case 9:y=3;i=2;o=3;break;case 10:y=5,i=2,o=5}m=i;for(q=0;0<j;){if(l>=a){if(0>=b)throw"Decompressing bitmap failed! Height = "+b;l=0;b--;e=k;k=0+b*a}switch(i){case 0:t&&(f[k+l]=-1==e?v:f[e+l]^v,t=!1,j--,l++);if(-1==e){for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)f[k+l]=0,j--,
l++;for(;0<j&&l<a;)f[k+l]=0,j--,l++}else{for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)f[k+l]=f[e+l],j--,l++;for(;0<j&&l<a;)f[k+l]=f[e+l],j--,l++}break;case 1:if(-1==e){for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)f[k+l]=v,j--,l++;for(;0<j&&l<a;)f[k+l]=v,j--,l++}else{for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)f[k+l]=f[e+l]^v,j--,l++;for(;0<j&&l<a;)f[k+l]=f[e+l]^v,j--,l++}break;case 2:if(-1==e){for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)q<<=1,q&=255,0==q&&(y=0!=o?o&255:d[n++],q=1),f[k+l]=0!=(y&q)?v:0,j--,l++;for(;0<j&&
l<a;)q<<=1,q&=255,0==q&&(y=0!=o?o&255:d[n++],q=1),f[k+l]=0!=(y&q)?v:0,j--,l++}else{for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)q<<=1,q&=255,0==q&&(y=0!=o?o&255:d[n++],q=1),f[k+l]=0!=(y&q)?f[e+l]^v:f[e+l],j--,l++;for(;0<j&&l<a;)q<<=1,q&=255,0==q&&(y=0!=o?o&255:d[n++],q=1),f[k+l]=0!=(y&q)?f[e+l]^v:f[e+l],j--,l++}break;case 3:for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)f[k+l]=r,j--,l++;for(;0<j&&l<a;)f[k+l]=r,j--,l++;break;case 4:for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)f[k+l]=Na(d,n,h),n+=h,j--,l++;for(;0<j&&l<
a;)f[k+l]=Na(d,n,h),n+=h,j--,l++;break;case 8:for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)s?(f[k+l]=r,s=!1):(f[k+l]=p,s=!0,j++),j--,l++;for(;0<j&&l<a;)s?(f[k+l]=r,s=!1):(f[k+l]=p,s=!0,j++),j--,l++;break;case 13:for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)f[k+l]=16777215,j--,l++;for(;0<j&&l<a;)f[k+l]=16777215,j--,l++;break;case 14:for(;0!=(j&-8)&&l+8<a;)for(w=0;8>w;w++)f[k+l]=0,j--,l++;for(;0<j&&l<a;)f[k+l]=0,j--,l++;break;default:throw"Unimplemented decompress opcode "+i;}}}return f}}function Oa(a,b,c,d,h,
e){var k,n,f,j,i,l,m,o,p=b,r=e;for(n=m=0;n<d;){e=r+4*c*d-4*(n+1)*c;i=0;o=e;k=0;if(0==m)for(;k<c;){f=a[b++]&255;j=f&15;f=f>>4&15;l=j<<4|f;47>=l&&16<=l&&(j=l,f=0);for(;0<f;)i=a[b++]&255,h[e]=i,e+=4,k++,f--;for(;0<j;)h[e]=i,e+=4,k++,j--}else for(;k<c;){f=a[b++]&255;j=f&15;f=f>>4&15;l=j<<4|f;47>=l&&16<=l&&(j=l,f=0);for(;0<f;)l=a[b++]&255,0!=(l&1)?(l>>=1,l+=1,i=-l):i=l>>=1,l=h[m+4*k]+i,h[e]=l,e+=4,k++,f--;for(;0<j;)l=h[m+4*k]+i,h[e]=l,e+=4,k++,j--}n++;m=o}return b-p}function ae(a,b,c,d){function h(a,b){var c=
a[b]&255,d=(a[b+1]&255)<<8|c,e=d>>8&248,d=d>>3&252,c=c<<3&255;return(e|e>>5)<<16|(d|d>>6)<<8|c|c>>5}for(var e=-1,k=-1,n=0,c=n+c,f=0,j=0,i=0,l=a,m=-1,o=0,p=j=0,r=0,v=i=0,t=4294967295,u=!1,q=!1,s=!1,w=Array(a*b);n<c;){o=0;j=d[n++]&255;f=j>>4;switch(f){case 12:case 13:case 14:f-=6;j&=15;i=16;break;case 15:f=j&15;9>f?(j=d[n++]&255,j|=(d[n++]&255)<<8):j=11>f?8:1;i=0;break;default:f>>=1,j&=31,i=32}0!=i&&(s=2==f||7==f,0==j?j=s?(d[n++]&255)+1:(d[n++]&255)+i:s&&(j<<=3));switch(f){case 0:m==f&&!(l==a&&-1==
e)&&(u=!0);break;case 8:p=h(d,n),n+=2;case 3:r=h(d,n);n+=2;break;case 6:case 7:t=h(d,n);n+=2;f-=5;break;case 9:v=3;f=2;o=3;break;case 10:v=5,f=2,o=5}m=f;for(i=0;0<j;){if(l>=a){if(0>=b)throw"Decompressing bitmap failed! Height = "+b;l=0;b--;e=k;k=0+b*a}switch(f){case 0:u&&(w[k+l]=-1==e?t:w[e+l]^t,u=!1,j--,l++);if(-1==e){for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)w[k+l]=0,j--,l++;for(;0<j&&l<a;)w[k+l]=0,j--,l++}else{for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)w[k+l]=w[e+l],j--,l++;for(;0<j&&l<a;)w[k+l]=w[e+
l],j--,l++}break;case 1:if(-1==e){for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)w[k+l]=t,j--,l++;for(;0<j&&l<a;)w[k+l]=t,j--,l++}else{for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)w[k+l]=w[e+l]^t,j--,l++;for(;0<j&&l<a;)w[k+l]=w[e+l]^t,j--,l++}break;case 2:if(-1==e){for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)i<<=1,i&=255,0==i&&(v=0!=o?o&255:d[n++]&255,i=1),w[k+l]=0!=(v&i)?t:0,j--,l++;for(;0<j&&l<a;)i<<=1,i&=255,0==i&&(v=0!=o?o&255:d[n++]&255,i=1),w[k+l]=0!=(v&i)?t:0,j--,l++}else{for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)i<<=
1,i&=255,0==i&&(v=0!=o?o&255:d[n++]&255,i=1),w[k+l]=0!=(v&i)?w[e+l]^t:w[e+l],j--,l++;for(;0<j&&l<a;)i<<=1,i&=255,0==i&&(v=0!=o?o&255:d[n++]&255,i=1),w[k+l]=0!=(v&i)?w[e+l]^t:w[e+l],j--,l++}break;case 3:for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)w[k+l]=r,j--,l++;for(;0<j&&l<a;)w[k+l]=r,j--,l++;break;case 4:for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)w[k+l]=h(d,n),n+=2,j--,l++;for(;0<j&&l<a;)w[k+l]=h(d,n),n+=2,j--,l++;break;case 8:for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)q?(w[k+l]=r,q=!1):(w[k+l]=p,q=!0,j++),
j--,l++;for(;0<j&&l<a;)q?(w[k+l]=r,q=!1):(w[k+l]=p,q=!0,j++),j--,l++;break;case 13:for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)w[k+l]=16777215,j--,l++;for(;0<j&&l<a;)w[k+l]=16777215,j--,l++;break;case 14:for(;0!=(j&-8)&&l+8<a;)for(s=0;8>s;s++)w[k+l]=0,j--,l++;for(;0<j&&l<a;)w[k+l]=0,j--,l++;break;default:throw"Unimplemented decompress opcode "+f;}}}return w}function Ad(a,b,c,d){for(var h=-1,e=0,k=0,n=0,f=0,j=0,i=a,l=-1,m=0,o=f=0,p=0,r=j=0,v=4294967295,t=!1,u=!1,q=!1,s=Array(a*b);k<c;){m=0;f=d[k++]&255;
n=f>>4;switch(n){case 12:case 13:case 14:n-=6;f&=15;j=16;break;case 15:n=f&15;9>n?(f=d[k++]&255,f|=(d[k++]&255)<<8):f=11>n?8:1;j=0;break;default:n>>=1,f&=31,j=32}0!=j&&(q=2==n||7==n,0==f?f=q?(d[k++]&255)+1:(d[k++]&255)+j:q&&(f<<=3));switch(n){case 0:l==n&&!(i==a&&-1==h)&&(t=!0);break;case 8:o=d[k++]&255;case 3:p=d[k++]&255;break;case 6:case 7:v=d[k++];n-=5;break;case 9:r=3;n=2;m=3;break;case 10:r=5,n=2,m=5}l=n;for(j=0;0<f;){if(i>=a){if(0>=b)throw"Decompressing bitmap failed! Height = "+b;i=0;b--;
h=e;e=0+b*a}switch(n){case 0:t&&(s[e+i]=-1==h?v&255:(s[h+i]^v&255)&255,t=!1,f--,i++);if(-1==h){for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=0,f--,i++;for(;0<f&&i<a;)s[e+i]=0,f--,i++}else{for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=s[h+i],f--,i++;for(;0<f&&i<a;)s[e+i]=s[h+i],f--,i++}break;case 1:if(-1==h){for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=v&255,f--,i++;for(;0<f&&i<a;)s[e+i]=v&255,f--,i++}else{for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++){var w=Sc(s,h,i)^v;s[e+i]=w&255;f--;i++}for(;0<f&&i<
a;)q=Sc(s,h,i)^v,s[e+i]=q&255,f--,i++}break;case 2:if(-1==h){for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)j<<=1,j&=255,0==j&&(r=0!=m?m&255:d[k++],j=1),s[e+i]=0!=(r&j)?v&255:0,f--,i++;for(;0<f&&i<a;)j<<=1,j&=255,0==j&&(r=0!=m?m&255:d[k++],j=1),s[e+i]=0!=(r&j)?v&255:0,f--,i++}else{for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)j<<=1,j&=255,0==j&&(r=0!=m?m&255:d[k++],j=1),s[e+i]=0!=(r&j)?(s[h+i]^v&255)&255:s[h+i],f--,i++;for(;0<f&&i<a;)j<<=1,j&=255,0==j&&(r=0!=m?m&255:d[k++],j=1),s[e+i]=0!=(r&j)?(s[h+i]^v&255)&255:
s[h+i],f--,i++}break;case 3:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=p&255,f--,i++;for(;0<f&&i<a;)s[e+i]=p&255,f--,i++;break;case 4:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=d[k++],f--,i++;for(;0<f&&i<a;)s[e+i]=d[k++],f--,i++;break;case 8:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)u?(s[e+i]=p&255,u=!1):(s[e+i]=o&255,u=!0,f++),f--,i++;for(;0<f&&i<a;)u?(s[e+i]=p&255,u=!1):(s[e+i]=o&255,u=!0,f++),f--,i++;break;case 13:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=255,f--,i++;for(;0<f&&i<a;)s[e+
i]=255,f--,i++;break;case 14:for(;0!=(f&-8)&&i+8<a;)for(q=0;8>q;q++)s[e+i]=0,f--,i++;for(;0<f&&i<a;)s[e+i]=0,f--,i++;break;default:throw"Unimplemented decompress opcode "+n;}}}return s}function Tb(){this.orderType=1;this.bounds=new BoundsOrder;this.destBlt=new DestBltOrder;this.patBlt=new PatBltOrder;this.screenBlt=new ScreenBltOrder;this.line=new LineOrder;this.rectangle=new RectangleOrder;this.deskSave=new DeskSaveOrder;this.memBlt=new MemBltOrder;this.triBlt=new TriBltOrder;this.polyLine=new PolyLineOrder;
this.text2=new Text2Order}this.displayMsg=this.reconnectOnResize=!0;this.sessionTimeout=3E5;this.appTimeout=800;this.reconnectTimes=0;this.windowState=3;this.setTitle=this.notification=this.openLink=!0;this.audioBuffer=2;var Z=null,r=this,Ra=null,Hb=null,Db="object"==typeof m?m:null,Va="object"==typeof m||0<m.indexOf("/PLAY?");Va?(Db?m="":(o=screen.width,u=screen.height),m+="&touchpad=on",this.reconnectOnResize=!1):0<m.indexOf("/JOIN?")&&(this.reconnectOnResize=!1);o||(o=window.innerWidth,u=window.innerHeight);
var Pa=hi5.tool.queryToObj(m.substring(m.indexOf("?")+1)),Ea=null;if(hi5.appcfg){var P=hi5.appcfg;"undefined"!==typeof P.displayMsg&&(this.displayMsg=P.displayMsg);"undefined"!==typeof P.sessionTimeout&&(this.sessionTimeout=P.sessionTimeout);"undefined"!==typeof P.appTimeout&&(this.appTimeout=P.appTimeout);"undefined"!==typeof P.reconnectOnResize&&(this.reconnectOnResize=P.reconnectOnResize);"undefined"!==typeof P.reconnectTimes&&(this.reconnectTimes=P.reconnectTimes);"undefined"!==typeof P.windowState&&
(this.windowState=P.windowState);"undefined"!==typeof P.openLink&&(this.openLink=P.openLink);"undefined"!==typeof P.notification&&(this.notification=P.notification);"undefined"!==typeof P.setTitle&&(this.setTitle=P.setTitle);"undefined"!=typeof P.audioBuffer&&(this.audioBuffer=P.audioBuffer)}this.displayMsg||(this.notification=!1);var o=parseInt(o),u=parseInt(u),p=p?parseInt(p):16,la={table:"A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(","),
pad:"=",enc:function(a,b){var c="",d=this.table,h=this.pad,e;if(!b)b=a.length;var k=b-1;for(e=0;e<k;e=e+3){c=c+d[a[e]>>2];c=c+d[((a[e]&3)<<4)+(a[e+1]>>4)];c=c+d[((a[e+1]&15)<<2)+(a[e+2]>>6)];c=c+d[a[e+2]&63]}if(b%3){e=b-b%3;c=c+d[a[e]>>2];if(b%3===2){c=c+d[((a[e]&3)<<4)+(a[e+1]>>4)];c=c+d[(a[e+1]&15)<<2];c=c+h}else{c=c+d[(a[e]&3)<<4];c=c+(h+h)}}return c},binaries:[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,
-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,0,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1],dec:function(a,b){var c=this.binaries,d=this.pad,h,e,k,m,f,j=0,i=0;h=a.indexOf("=")-b;var l=a.length;h<0&&(h=l-b);h=Array((h>>2)*3+Math.floor(h%4/1.5));e=0;for(k=b;k<l;k++){m=c[a.charCodeAt(k)&127];f=a.charAt(k)===d;if(m===-1)svGlobal.log>0&&console.error("Illegal character '"+
a.charCodeAt(k)+"'");else{i=i<<6|m;j=j+6;if(j>=8){j=j-8;f||(h[e++]=i>>j&255);i=i&(1<<j)-1}}}if(j)throw"Invalid base64 encoding";return h}},Ta={historyoff:0,history:Array(65536),currOff:0,currLen:0,reset:function(){this.historyoff=0;this.history=Array(65536);this.currLen=this.currOff=0},getData:function(){var a=new RdpBuffer(this.history,this.currOff,this.currLen);a.markEnd(this.currOff+this.currLen);return a},dec:function(a,b,c,d){var h,e=0,k=0,m,f,j,i,l=(d&1)!=0,o=this.history;if((d&32)==0){this.currOff=
0;this.currLen=c;return 0}if((d&64)!=0)this.historyoff=0;if((d&128)!=0){for(d=65536;--d>=0;)o[d]=0;this.historyoff=0}this.currLen=this.currOff=0;this.currOff=j=m=d=this.historyoff;if(c==0)return 0;c=c+k;do{if(e==0){if(k>=c)break;d=(a[b+k++]&255)<<24;e=8}if(d>=0){if(e<8){if(k>=c){if(d!=0)return-1;break}d=d|(a[b+k++]&255)<<24-e;e=e+8}if(m>=65536)return-1;o[m++]=d>>>24&255;d=d<<8;e=e-8}else{d=d<<1;if(--e==0){if(k>=c)return-1;d=(a[b+k++]&255)<<24;e=8}if(d>=0){if(e<8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<
24-e;e=e+8}if(m>=65536)return-1;o[m++]=(d>>>24|128)&255;d=d<<8;e=e-8}else{d=d<<1;if(--e<(l?3:2)){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e;e=e+8}if(l)switch(d>>>29){case 7:for(;e<9;e=e+8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e}d=d<<3;h=d>>>26;d=d<<6;e=e-9;break;case 6:for(;e<11;e=e+8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e}d=d<<3;h=(d>>>24)+64;d=d<<8;e=e-11;break;case 5:case 4:for(;e<13;e=e+8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e}d=d<<2;h=(d>>>21)+320;d=d<<11;e=e-13;break;default:for(;e<
17;e=e+8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e}d=d<<1;h=(d>>>16)+2368;d=d<<16;e=e-17}else switch(d>>>30){case 3:if(e<8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e;e=e+8}d=d<<2;h=d>>>26;d=d<<6;e=e-8;break;case 2:for(;e<10;e=e+8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e}d=d<<2;h=(d>>>24)+64;d=d<<8;e=e-10;break;default:for(;e<14;e=e+8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e}h=(d>>>18)+320;d=d<<14;e=e-14}if(e==0){if(k>=c)return-1;d=(a[b+k++]&255)<<24;e=8}if(d>=0){f=3;d=d<<1;e--}else{i=l?14:11;
do{d=d<<1;if(--e==0){if(k>=c)return-1;d=(a[b+k++]&255)<<24;e=8}if(d>=0)break;if(--i==0)return-1}while(1);f=(l?16:13)-i;d=d<<1;if(--e<f)for(;e<f;e=e+8){if(k>=c)return-1;d=d|(a[b+k++]&255)<<24-e}i=f;f=d>>>32-i&~(-1<<i)|1<<i;d=d<<i;e=e-i}if(m+f>=65536)return-1;h=m-h&(l?65535:8191);do o[m++]=o[h++];while(--f!=0)}}}while(1);this.historyoff=m;this.currOff=j;this.currLen=m-j;return 0}},Ud=0<m.indexOf("nocurosr=on"),U=0<m.indexOf("startProgram=app"),Gb=0<m.indexOf("mapDisk=on"),ha=null;this.server=Pa.server;
this.port=parseInt(Pa.port);U&&(this.reconnectOnResize=!1);this.isRemoteApp=function(){return U};if(U)if(hi5.browser.isTouch){var be=Math.max(screen.width,screen.height),ce=Math.max(o,u),Qa=Math.max(be,ce);o<Qa&&(o=Qa);u<Qa&&(u=Qa)}else o=screen.width,u=screen.height,1==r.windowState&&(u-=window.outerHeight-window.innerHeight+25);else o&=-4,u&=-4;var t=null,Aa=null,L=!1,Ca=!1,B=null,ca=new function(a){var b=null;this.available=false;this.delay=a;if(hi5.browser.isTouch)this.available=false;else if("webkitAudioContext"in
window){b=new webkitAudioContext;this.available=true}else if("AudioContext"in window){b=new AudioContext;this.available=true}else if(hi5.browser.isFirefox){this.available=true;return}if(this.available){this.getBuffer=function(a){return b.createBuffer(2,a,J)};var c=0;this.playBuffer=function(d){var h=b.createBufferSource();h.buffer=d;h.connect(b.destination);var e=b.currentTime,k=c>0?c:e+a;k<e&&(k=e+a);c=k+d.duration;h.noteOn(k);return c-e}}}(r.audioBuffer);this.setAudioBuffer=function(a){r.audioBuffer=
a;ca.delay=a;if(pa)pa.delay=a};for(var pa=null,tc=Array(12),pc=0;12>pc;pc++)tc[pc]=Array(256);var Ub=Array(256),O=0,N=0,H=o-1,E=u-1,ga=null,Ba=null,Ua,Yc=0;window.rdpConnection=this;var oa=qc;Rb(p);this.running=function(){return L};this.hide=function(){z&&z.hide()};var Da=new function(){this.ws=null;this.clipRequired=this.prePaste=false;this.send=function(a){L&&this.ws.send(a)};var a=null;this.getAppInfo=function(){return Ua};this.onresize=function(b){var c=b.target.innerWidth,d=b.target.innerHeight;
if(U){if(b.target.svSurface){b=b.target.svSurface.railWin.getMain(z.zOrders);b!=null&&Oc(b,c,d)}}else if(!hi5.browser.isTouch&&!hi5.browser.isOpera&&r.reconnectOnResize&&L){if(a){clearTimeout(a);a=null}a=setTimeout(function(){Vb(c,d)},1E3)}};this.onorientationchange=function(a){if(r.reconnectOnResize)Vb(window.innerWidth,window.innerHeight);else if(U&&a.target.svSurface){var c=a.target.svSurface.railWin.getMain(z.zOrders);c!=null&&Oc(c,a.target.innerWidth,a.target.innerHeight)}};this.getClipData=
$c;this.setDataFromClip=function(a){Aa=a;if(this.prePaste&&this.clipRequired){t.send("881"+a);Aa="";this.clipRequired=false}this.prePaste=false};this.onfocus=function(a){if(U){var c=a.target.svSurface.railWin.getTopWin(z.zOrders);if(!(c==null||t==null)){c.activate(1);svGlobal.log>1&&console.log("Activate win:"+c.id);Ra=a.target.svSurface.context}}};this.fileCallback=[];this.getShareFiles=function(a,c){if(Ca){this.ws.send("3A5"+a);this.fileCallback.push(c)}};this.notifyFiles=function(a){for(var c=
this.fileCallback,d=0,h=c.length;d<h;d++)c[d](a)};this.getFile=function(a){r.reconnectOnResize=false;window.open(lb()+"/DOWNLOAD?s="+Ba+"&f="+a)};this.getGateway=function(){return m}},z=function(){var a=[];a.addSurface=function(b){b.railWin=new ad;a.push(b)};a.zOrders=[];a.drawLicense=function(b){for(var c=0,d=a.length;c<d;c++)a[c].drawLicense(b)};a.removeEvents=function(){for(var b=0,c=a.length;b<c;b++)a[b]&&a[b].removeEvents()};a.setConnected=function(b){for(var c=0,d=a.length;c<d;c++)a[c].setConnected(b)};
a.setReadOnly=function(b){for(var c=0,d=a.length;c<d;c++)a[c].setReadOnly(b)};a.setVisible=function(){svGlobal.log>1&&console.log("TODO: setVisible")};a.copyToClip=function(b){a.length<1||a[0].copyToClip(b)};a.setCursor=function(b){U||a[0].setCursor(b);var c=a.getFocused();c!=null&&c.setCursor(b)};a.hide=function(){if(U)for(var b=0,c=a.length;b<c;b++)a[b].browser.close();else a[0].hide()};a.execute=function(b,c){for(var d=0,h=a.length;d<h;d++)a[d][b].apply(a[d],c)};a.addWin=function(b){var c=a.getFocused();
if(!c){console.log("Focusd surface not found!");c=a[a.length-1]}if(c){c.railWin.addWin(b);c.setConnected(true);if(function(){var a=b.ownerWinid<1;if(!a)return a;if(b.showState===0)return false;var c=b.style;if((c&4194304)!=0)return true;var e=(b.extStyle&128)!=0;(a=a&&!e)&&(c&2147483648)!=0&&(c&2156396544)==0&&(a=false);svGlobal.log>1&&console.log("*** win id="+b.id+" isMain="+a);return a}()){if("titleInfo"in b&&r.setTitle)c.browser.document.title=b.titleInfo+" - "+r.server;b.fillBrowser();b.activate(1)}else b.checkBound()}else console.log("No surface available!")};
a.delWin=function(b){for(var c,d=a.length-1;d>=0;d--){c=a[d].railWin;if(c.delWin(b)>=0)if(c.isRunning()){var h=c.getMain(a.zOrders);h&&h.fillBrowser();(h=c.getTopWin(a.zOrders))&&h.activate(1)}else{var e=a[d];setTimeout(function(){e.railWin.isRunning()||a.delSurface(e)},r.appTimeout)}}};a.getWinById=function(b){for(var c,d=0,h=a.length;d<h;d++)if(c=a[d].railWin.getWinById(b))return c;return null};a.delSurface=function(b){if(!b.railWin.isRunning()){svGlobal.log>1&&console.log("delete surface...");
a.removeElm(b);b.close()}};a.getOwnerSurface=function(b){for(var c=0,d=a.length;c<d;c++)if(a[c].railWin.hasWin(b))return a[c];return null};a.getFocused=function(){if(!U)return a[0];for(var b=a.length,c=0;c<b;c++)if(a[c].focused)return a[c];return a[b-1]};a.close=function(){for(var b=0,c=a.length;b<c;b++)a[b]&&a[b].close()};return a}();this.getSurfaces=function(){return z};this.exeAppCmd=function(a){var b=z.getFocused();b&&b.exeCommand(a)};this.setJoinMode=function(a){L&&t.send("8E1"+a)};this.addSurface=
function(a){Ra=a.context;Va&&a.setPlayerMode();a.setSize(o,u,U?"hidden":null);a.setController(Da);a.setFastCopy(Pa.fastCopy=="on");a.setTouchpad(Pa.touchpad=="on");if(Gb){a.setFileHandler(uc);ha==null&&(ha=new Wb(new vc))}a.run(m.indexOf("keyboard=99999")>0);z.addSurface(a)};this.getRunninApps=function(){for(var a=[],b=0,c=z.length;b<c;b++)z[b].railWin.getMain(z.zOrders)!=null&&a.push(z[b].railWin.getMain(z.zOrders).titleInfo);return a};this.startApp=function(a,b,c){t.send("8C2"+a+"\t"+b+"\t"+c);
var d=z[z.length-1];if(d)d.remoteApp={exe:a,args:b,dir:c}};this.VirtualChannel=function(){this.send=function(a){a=a.getData();t.send("8F"+la.enc(a,a.length))}};this.addChannel=function(a){a.rdp=r;Z=a};this.run=function(){if(!L){Ca=false;if(Db)t=Db;else{var a=m+"&width="+o+"&height="+u+"&server_bpp="+p+"&audio="+ca.available+ib();m.indexOf("waWidth")<0&&(a=a+(U?"&waWidth="+o+"&waHeight="+u:""));var b=new Date,a=a+("&tzOffset="+b.getTimezoneOffset()+"&time="+b.getTime());(b=hi5.browser.binaryWS(a.substring(0,
a.indexOf("/",6))))&&(a=a+"&binary=on");if(Z){a=a+("&channelName="+Z.name);Z.flags&&(a=a+("&channelFlags="+Z.flags))}var c=window.opener;if(c){var d=null;try{d=c.__sparkUser}catch(h){}if(d){c=d.account;d=d.session;c&&(a=a+("&account="+c));d&&(a=a+("&session="+d))}}t=new hi5.WebSocket(a);if(b)t.binaryType="arraybuffer"}Da.ws=t;B=Eb(o,u);svGlobal.log>1&&console.log(m);t.onopen=Nd;t.onmessage=Od;t.onclose=function(a){svGlobal.log>1&&console.log("closed, code="+a.code+" reason="+a.reason);L||rc("connection");
if(r.reconnectTimes){r.reconnectTimes--;L=true;Vb(window.innerWidth,window.innerHeight)}else{L=false;try{z&&z.close()}catch(b){}window&&delete window.rdpConnection;if(r&&r.onclose)r.onclose()}};t.onerror=Md;a=z[z.length-1];if(U){if(a)a.remoteApp={exe:Pa.exe,args:Pa.args,dir:""}}else if(r.setTitle)a.browser.document.title=r.server}};this.getDesktop=function(){return B};this.mouseDown=function(a,b,c){L&&t.send("80"+a+"\t"+b+"\t"+c)};this.mouseMove=function(a,b){L&&t.send("82"+a+"\t"+b)};this.mouseUp=
function(a,b,c){L&&t.send("81"+a+"\t"+b+"\t"+c)};this.writeKeyCode=function(a,b){L&&t.send("8B"+(a?0:49152)+"\t"+b)};this.writeScancode=function(a,b){if(L)if(typeof a=="number"){t.send("840\t"+a);t.send("8449152\t"+a)}else t.send("84"+(a?0:49152)+"\t"+b)};this.writeText=function(a){L&&t.send("86"+a)};this.refuseControl=function(a){L&&t.send("8E3"+a)};this.giveControl=function(a){L&&t.send("8E4"+a)};this.requestControl=function(){L&&t.send("8E2")};var ac=0;this.play=function(){t.send("F3")};this.pause=
function(){t.send("F2")};this.scan=function(a){t.send("F4"+(a?"1":"0"))};J=x=v=D=0;this.showMessage=function(a){var b=z.getFocused();b?b.showMessage(a):hi5.notifications.notify({msg:a})};var X=new Tb,Sa=0,sc=null;this.close=Pc;window.addEventListener("unload",Pc,!1);var G=16777215,jb=[],kb=Array(20)}
function RdpBuffer(m,o,u){var p=o,x=o+u;this.markEnd=function(){x=getPosition()};this.markEnd=function(m){x=m};this.getEnd=function(){return x};this.getStart=function(){return start};this.setStart=function(m){start=m};this.getByte=function(){return m[p++]&255};this.getBytes=function(o){var u;if(m.slice)u=m.slice(p,p+o);else if(m.buffer&&m.buffer.slice)u=new Int8Array(m.buffer.slice(p,p+o));else{u=Array(o);for(var x=0;x<o;x++)u[x]=m[p+x]}p+=o;return u};this.getCapacity=function(){return m.length};
this.size=function(){return u};this.getPosition=function(){return p};this.getLittleEndian16=function(){var o=(m[p+1]&255)<<8|m[p]&255;p+=2;return o};this.getBigEndian16=function(){var o=(m[p]&255)<<8|m[p+1]&255;p+=2;return o};this.getLittleEndian32=function(){var o=(m[p+3]&255)<<24|(m[p+2]&255)<<16|(m[p+1]&255)<<8|m[p]&255;p+=4;return o};this.getLittleEndian64=function(){var o=(m[p+7]&255)<<56|(m[p+6]&255)<<48|(m[p+5]&255)<<40|(m[p+4]&255)<<32|(m[p+3]&255)<<24|(m[p+2]&255)<<16|(m[p+1]&255)<<8|m[p]&
255;p+=8;return o};this.getBigEndian32=function(){var o=(m[p]&255)<<24|(m[p+1]&255)<<16|(m[p+2]&255)<<8|m[p+3]&255;p+=4;return o};this.getUnicodeString=function(m,o){for(var p=Math.floor(m/2),u="",x=0;x<p;x++){var ib=this.getLittleEndian16();if(o&&0==ib){this.skipPosition(2*(p-x-1));break}u+=String.fromCharCode(ib)}return u};this.skipPosition=function(m){p+=m};this.setPosition=function(m){p=m};this.getData=function(){return m};this.setByte=function(o){m[p++]=o};this.setLittleEndian16=function(o){m[p++]=
o&255;m[p++]=o>>8&255};this.setLittleEndian32=function(o){m[p++]=o&255;m[p++]=o>>8&255;m[p++]=o>>16&255;m[p++]=o>>24&255}}function Brush(){this.style=this.yOrigin=this.xOrigin=0;this.pattern=Array(8)}function BoundsOrder(){this.bottom=this.top=this.right=this.left=0}function DeskSaveOrder(){this.action=this.offset=this.bottom=this.top=this.right=this.left=0}function DestBltOrder(){this.opcode=this.cy=this.cx=this.y=this.x=0}
function FontData(m,o,u,p,x,v,D){this.font=m;this.character=o;this.offset=u;this.baseline=p;this.width=x;this.height=v;this.fontdata=D}function LineOrder(){this.opcode=this.backgroundColor=this.endY=this.endX=this.startY=this.startX=this.mixmode=0;this.pen=new Pen}function MemBltOrder(){this.cacheIDX=this.cacheID=this.colorTable=this.srcY=this.srcX=this.opcode=this.cy=this.cx=this.y=this.x=0}function PaletteData(m,o,u,p,x){this.bits=m;this.size=o;this.red=u;this.green=p;this.blue=x}
function PatBltOrder(){this.foregroundColor=this.backgroundColor=this.opcode=this.cy=this.cx=this.y=this.x=0;this.brush=new Brush}function Pen(){this.color=this.width=this.style=0}function PolyLineOrder(){this.dataSize=this.opcode=this.lines=this.foregroundColor=this.flags=this.y=this.x=0;this.data=Array(256)}function RectangleOrder(){this.color=this.cy=this.cx=this.y=this.x=0}function ScreenBltOrder(){this.srcY=this.srcX=this.opcode=this.cy=this.cx=this.y=this.x=0}
function Text2Order(){this.length=this.opcode=this.boxBottom=this.boxRight=this.boxTop=this.boxLeft=this.clipBottom=this.clipRight=this.clipTop=this.clipLeft=this.font=this.unknown=this.y=this.x=this.backgroundColor=this.foregroundColor=this.mixmode=this.flags=0;this.text=Array(256)}function TriBltOrder(){this.foregroundColor=this.backgroundColor=this.opcode=this.cy=this.cx=this.y=this.x=0;this.brush=new Brush;this.unknown=this.srcY=this.srcX=this.cacheIDX=this.cacheID=this.colorTable=0}
var Connection={KEY_IDS:"__CONNS",KEY_TIMESTAMP:"__TIMESTAMP",hasStorage:"localStorage"in window,getAll:function(){var m=localStorage[this.KEY_IDS];return null==m?[]:m.split(",")},saveForm:function(m){for(var m=m.elements,o=m.length,u={},p=null,x=0;x<o;x++){var v=m[x];if("button"!=v.type){var D=v.name,J=v.value;"server"==D&&(p=J);if("checkbox"==v.type)J=v.checked;else if("radio"==v.type&&!v.checked)continue;if("width"==D&&(J=parseInt(J),J==window.innerWidth||J==screen.width))continue;if("height"==
D&&(J=parseInt(J),J==window.innerHeight||J==screen.height))continue;"pwd"!=D&&(u[D]=J)}}return this.save(p,u)?p:null},save:function(m,o){if(null==m)return!1;var u=localStorage[m];localStorage[m]=JSON.stringify(o);var p=localStorage[this.KEY_IDS];null==p?p=m:null==u&&(p=p+","+m);localStorage[this.KEY_IDS]=p;return!0},loadToForm:function(m,o){if(null==o)return!1;var u=localStorage[o];if(null==u)return!1;for(var u=JSON.parse(u),p=m.elements,x=0,v=p.length;x<v;x++){var D=p[x],J=D.type;if(!("button"==
J||"submit"==J)){var ea=D.name,C=u[ea];if("undefined"==typeof C){if("gateway"!=ea)switch(J){case "text":D.value="";break;case "checkbox":D.checked=!1;case "radio":D.checked=!1}}else"startProgram"==ea?"shell"==D.id?(D.checked=!0==C||"shell"==C,D.value="shell"):D.checked=C==D.id:"checkbox"==J?D.checked=C:D.value=C}}return!0},clear:function(){localStorage.clear()},remove:function(m){localStorage.removeItem(m);for(var o=this.getAll(),u="",p=0,x=o.length;p<x;p++)m!=o[p]&&(""!=u&&(u+=","),u+=o[p]);localStorage[this.KEY_IDS]=
u},getValue:function(m){return this.hasStorage?localStorage[m]:null},setValue:function(m,o){localStorage[m]=o},removeItem:function(m){localStorage.removeItem(m)}};svGlobal.Rdp=Rdp;
