var svGlobal={version:"2.6",log:1,isMultitask:hi5.browser.isMultitask,util:{}},isTouch=hi5.browser.isTouch;
function LocalInterface(){function f(a){var b=0,c=0,e=0,d=0,h=!1,g=0,i=0,j=0,k=0,K=0,f=!1,o=!1;this.delay=!1;this.handle=function(m){m.preventDefault();m.stopPropagation();var n=0,l=m.touches,n=m.changedTouches,p;switch(m.type){case "touchstart":c=l.length;o=!1;d=(new Date).getTime();h=200>d-e;m=l[0];b=m.identifier;i=m.pageX;j=m.pageY;f=!0;g=0;40>m.clientX?g=1:40>m.clientY?g=2:m.clientX>window.innerWidth-40?g=3:m.clientY>window.innerHeight-40&&(g=4);break;case "touchmove":if(g&&o)break;m=l[0];l=m.pageX;
p=m.pageY;if(f){if(5>Math.abs(l-i)&&5>Math.abs(p-j))break;f=!1;n=(new Date).getTime()-d;o=250>n;if(g&&o)break;a.touchstart({x:i,y:j,flick:o,pointes:c,screenX:m.screenX,screenY:m.screenY})}a.touchmove({x:l,y:p,flick:o,pointes:c,screenX:m.screenX,screenY:m.screenY});break;case "touchend":m=null;l=0;for(p=n.length;l<p;l++)if(n[l].identifier==b){m=n[l];break}if(m){var q=(new Date).getTime(),l=m.pageX;p=m.pageY;o?g&&o?a.flick({start:{x:i,y:j},end:{x:l,y:p},pointes:c,from:g}):a.touchend({x:l,y:p,flick:!0,
pointes:c,moved:!f,screenX:m.screenX,screenY:m.screenY}):(n=q-d,f)?(e=q,h||(k=l,K=p),500>n)?(e=q,a.touchstart({x:k,y:K,flick:!1,pointes:c,moved:!f,screenX:m.screenX,screenY:m.screenY}),a.touchend({x:k,y:K,flick:!1,pointes:c,moved:!f,screenX:m.screenX,screenY:m.screenY})):a.longpress({x:l,y:p,flick:!1,pointes:c,screenX:m.screenX,screenY:m.screenY}):a.touchend({x:l,y:p,flick:!1,pointes:c,moved:!f,screenX:m.screenX,screenY:m.screenY})}break;case "touchcancel":console.log("canceled!!")}}}function s(){e||
(e=document.createElement("img"),e.alt="+",e.style.position="absolute",e.style.left=90,e.style.top=90,e.scrX=0,e.scrY=0,e.hotX=0,e.hotY=0,U&&(e.src=U.data),document.documentElement.appendChild(e),1<svGlobal.log&&console.log("imgCursor: enabled"),e.addEventListener("touchstart",x,!1),e.addEventListener("touchend",x,!1),e.addEventListener("touchmove",x,!1),e.addEventListener("touchcancel",x,!1))}function n(){j.toolbar&&j.toolbar.parentNode&&(j.toolbar.parentNode.removeChild(j.toolbar),j.toolbar=null)}
function N(){var a=document.createElement("div");a.contentEditable="true";a.style.position="absolute";a.style.zIndex=89;a.style.left=0;a.style.top=0;a.tabIndex=1;a.style.outline="none";a.style.opacity=0;g.parentNode.appendChild(a);return a}function t(a){j.focused=!0;i.onfocus(a);V=!0;null==d||hi5.browser.isOpera||!p||(k(!1,29),k(!1,56),k(!1,42),setTimeout(function(){if(!("undefined"==typeof i||null==i)){i.send("880");var a=N();try{a.focus();document.execCommand("paste",!1,null);var c="";"innerText"in
a?c=a.innerText:(c=a.innerHTML,c=q(c));0<c.length&&i.setDataFromClip(c)}catch(e){}finally{a.parentNode.removeChild(a),d.focus()}}},3))}function J(a){var b=aa||!j.railWin||!j.railWin.isRunning()?null:__svi18n.remoteApp.close;a&&(a.returnValue=b);b&&hi5.browser.isFirefox&&hi5.notifications.show({msg:b});return b}function l(){document.oncontextmenu=function(){return!1};document.onselectstart=function(){return!1}}function ma(){window.addEventListener("beforeunload",J,!1);l();window.addEventListener("focus",
t,!1);window.addEventListener("blur",function(){j.focused=!1},!1);window.onresize=i.onresize}function I(a){var b=hi5.browser;b.isFirefox||b.isOpera||b.isRIM?a.addEventListener("input",ba,!1):a.addEventListener("textInput",ca,!1)}function na(){var a=hi5.browser.isRIM;o=document.createElement(a?"input":"textarea");a&&(o.type="password");o.style.resize="none";o.cursor="default";o.style.opacity=0;o.style.width="1px";o.style.height="1px";o.onkeydown=da;o.onkeyup=da;o.autocorrect="boolean"==typeof o.autocorrect?
!1:"off";o.autocomplete="boolean"==typeof o.autocomplete?!1:"off";o.spellcheck=!1;o.autocapitalize="boolean"==typeof o.autocapitalize?!1:"off";I(o)}function A(a,b){function c(a,c){var e=document.createElement("span");e.data_path=a;e.className="path";e.innerHTML=c;e.onclick=function(){A(this.data_path,b)};return e}function e(a){for(var b=d;b.hasChildNodes();)b.removeChild(b.firstChild);var g=c("/","&nbsp&nbsp&nbsp/");b.appendChild(g);if(!("/"==a||""==a))for(var a=a.split("/"),h="/",i=0,j=a.length;i<
j;i++)g=a[i],""!=g&&(h=h+a[i]+"/",g=c(h,g+"/"),b.appendChild(g))}var d=document.getElementById("parentPath");d.currentDir||(d.currentDir="/");"."==a?a=d.currentDir:d.currentDir=a;d.currentDir=a;i.getShareFiles(a,function(a){a.error&&alert(__svi18n.file[a.error]);var c=new hi5.DataTable(a),d=new hi5.DataGrid(document.getElementById("filelist"));d.dataTable=c;var g=hi5.tool.bytesToSize;d.beforeDisplayValue=function(a,b){var d=c.cols[a].name;return d=="Date Modified"?(new Date(b)).toLocaleString():d==
"Size"?g(b):d=="Type"&&"folder"==b?__svi18n.file.folder:b};d.onrowclick=function(c){var e=d.getValue("Name");if(d.getValue("Type")=="folder")A((a.parent=="/"?"":a.parent)+"/"+e,b);else{var g=a.parent;if(g==""||g.charAt(g.length-1)!="/")g=g+"/";g=g+e;c.target.name=="view"&&(g=g+"&action=view");i.getFile(g)}};d.beforeAppendRow=function(a){if(c.getValue(c.getColNo("Type"))=="folder")a.getElementsByTagName("img")[0].style.visibility="hidden"};d.open();e(a.parent);b.resize()})}function K(){var a=document.getElementById("filecontainer");
u=new hi5.Lightbox(a);A(".",u);u.show()}function oa(){o&&o.focus()}function r(){var a=hi5.$("appinfo");if(j.showToolbar&&(hi5.browser.isTouch||v||a)){j.toolbar=new hi5.Toolbar;var b=hi5.appcfg,c=b&&b.img?b.img:null;hi5.browser.isTouch&&j.toolbar.addButton(c&&c.kbd?c.kbd:"kbd.png",oa);v&&(c=j.toolbar.addButton(c&&c.cloud?c.cloud:"cloud.png",K),c.title=__svi18n.info.files);new hi5.Dragable(j.toolbar);hi5.browser.isTouch&&(j.toolbar.appendChild(o),j.toolbar.activeObj=o);document.documentElement.appendChild(j.toolbar);
new hi5.Fadable(j.toolbar,3E3,hi5.browser.isTouch?g:d);c=!0;b&&b.toolbar&&(c=b.toolbar.fadable);j.toolbar.setFadable(c);c&&(j.toolbar.style.display="none");c=function(){var a=i.getAppInfo(),b=hi5.$("numericId");if(b)b.innerHTML=a.numericId;if(b=hi5.$("connectingTo"))b.innerHTML=a.server;if(b=hi5.$("joinLink")){var c=hi5.appcfg&&hi5.appcfg.pageJoin?hi5.appcfg.pageJoin:"join.html",c=location.protocol+"//"+location.host+"/"+c+"?id="+a.numericId,d=i.getGateway(),a=d.indexOf("://"),d=d.substring(a+3),
a=d.indexOf("/");a>0&&(d=d.substring(0,a));d!=location.host&&(c=c+("&gateway="+d));b.innerHTML=c;b.href=c}b=new hi5.Lightbox(hi5.$("appinfo"));b.show();document.oncontextmenu=null;document.onselectstart=null;b.onclose=l};a&&(c=j.toolbar.addButton(b&&b.img&&b.img.shadowing?hi5.appcfg.img.shadowing:"info.png",c),c.title=__svi18n.info.info);j.toolbar.resize()}}function B(){var a=hi5.browser.isTouch?g:d;v&&!C&&(svGlobal.util.initMapDisk(a,v),svGlobal.util.initMapDisk(document.getElementById("filecontainer"),
v),document.getElementById("uploadfile").addEventListener("change",function(a){v(a.target.files)},!1))}function q(a){a=a.replace(/<br\/?>/gi,"\r\n").replace(/(<([^>]+)>)/gi,"");return a.replace(/&[^;]+;/gi,function(a){return pa[a]||a})}function h(a){a.preventDefault();a.stopPropagation();return!1}function D(a,b,c){a=e.scrX+a;b=e.scrY+b;0>a?a=0:a>E&&(a=E-1);0>b?b=0:b>y&&(b=y-1);e.scrX=a;e.scrY=b;e.style.left=g.offsetLeft+a-e.hotX+"px";e.style.top=g.offsetTop+b-e.hotY+"px";p&&!c&&i.send("82"+a+"\t"+
b)}function O(a,b,c){e||s();D(a-e.scrX,b-e.scrY,c)}function W(a,b,c,d){switch(a){case "touchstart":X=!1;touchStartX=b;touchStartY=c;0==e.scrX&&0==e.scrY&&O(b-50,c-50);d&&i.send("80"+e.scrX+"\t"+e.scrY+"\t0");break;case "touchmove":X=!0;D(b-F,c-z);break;case "touchend":(a=!X&&!d)&&i.send("80"+e.scrX+"\t"+e.scrY+"\t0"),(a||d)&&i.send("81"+e.scrX+"\t"+e.scrY+"\t0")}F=b;z=c}function x(a){p&&ea.handle(a)}function Y(a){if(hi5.browser.isFirefox){switch(a){case 109:return 189;case 107:return 187;case 59:return 186;
case 61:return Z?187:61;case 220:return Z?222:220;case 222:return Z?192:222;case 224:return 17}return a}if(hi5.browser.isOpera){switch(a){case 59:return 186;case 61:return 187;case 109:return 189;case 219:return 91;case 57351:return 93}return a}return 91==a||93==a?17:a}function P(a){var b=a.keyCode,c="keydown"==a.type;if(fa(a,b,c))return h(a);if(17==b){if(a.altKey)return!0;k(c,29);return!0}if(18==b){if(a.ctrlKey)return!0;k(c,56);k(!1,56);k(!1,29);return!0}if(a.ctrlKey&&a.altKey)return!0;var b=Y(b),
e=$(b);if(0<e)return k(c,e),h(a);if(a.ctrlKey||a.altKey)return Q(c,b),c&&(R=b),17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(c&&67==b&&(d.value="A",d.select()),!0):h(a);if(b==R&&!c)return Q(!1,b),R=0,h(a);R=0;return!0}function fa(a,b,c){if(!a.altKey)return!1;switch(b){case 35:if(!a.ctrlKey)return!1;k(c,83);break;case 33:k(c,15);break;case 34:c?(k(!0,42),k(!0,15)):(k(!1,15),k(!1,42));break;case 45:k(c,1);break;case 36:c?(k(!1,56),k(!0,29),k(!0,1)):(k(!1,1),k(!1,29));break;default:return!1}return!0}
function S(a){if(!p)return!1;var b=a.keyCode,c="keydown"==a.type;if(fa(a,b,c))return h(a);if(229<=b)return c&&a.ctrlKey?k(!0,29):k(!1,29),!0;if(1>b)return!0;b=Y(b);if(ga(b,c))return h(a);var e=$(b);0<e?k(c,e):Q(c,b);c&&a.altKey&&31<b&&(Q(!1,b),k(!1,56));return 17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(c&&67==b&&(d.value="A",d.select()),!0):144==b?!1:h(a)}function da(a){if(!p)return!1;var b=Y(a.keyCode),c="keydown"==a.type;if(!ga(b,c)){13==b&&(a.target.value="");b=$(b);if(-1==b)return!0;
k(c,b)}return h(a)}function ca(a){if(p){var b=a.data;i.send("86"+b);if(!isTouch||"."==b[b.length-1])a.target.value=""}}function ba(a){if(!p)return!1;i.send("86"+a.target.value);a.target.value="";return h(a)}function qa(a){if(!p||!V)return h(a);V=!1;i.prePaste=!0;if("clipboardData"in a)return i.setDataFromClip(a.clipboardData.getData("text/plain")),h(a);var b=a.target,c=b.value;hi5.browser.isFirefox||hi5.browser.isOpera?b.removeEventListener("input",ba,!1):b.removeEventListener("textInput",ca,!1);
var d=function(){b.value==c&&setTimeout(d,5);i.setDataFromClip(b.value);b.value="";I(b)};setTimeout(d,5);return!0}function ha(a){if(p){if(ia){var b=(new Date).getTime(),c=b-ja;ja=b;if(500<c)return}a.target.value=i.getClipData();a.target.select();setTimeout(function(){d.value=""},555)}}function ga(a,b){return 44==a?(k(!0,170),k(!0,183),!0):19==a?(b?(k(!0,225),k(!0,29),k(!0,69),k(!0,225),k(!0,157),k(!0,197)):k(!1,29),!0):!1}function k(a,b){G&&p&&i.send("84"+(a?0:49152)+"\t"+b)}function Q(a,b){G&&p&&
i.send("8B"+(a?0:49152)+"\t"+b)}function ra(a){a.target.focus();if(!p||!G)return!1;var b=a.pageX-g.offsetLeft,c=a.pageY-g.offsetTop;if(j.railWin){var d=j.railWin.winClientDeltaX;L=b<=d||b>=window.innerWidth-d||c<=d||c>=window.innerHeight-d}else L=!1;if(L)return!1;i.send("80"+b+"\t"+c+"\t"+a.button);return h(a)}function sa(a){if(!p||!G)return!1;e&&"-30px"!=e.style.left&&(e.style.left="-30px");i.send("82"+(a.pageX-g.offsetLeft)+"\t"+(a.pageY-g.offsetTop));return h(a)}function ta(a){if(!p||!G)return!1;
if(L)return L=!1;i.send("81"+(a.pageX-g.offsetLeft)+"\t"+(a.pageY-g.offsetTop)+"\t"+a.button);return h(a)}function ka(a){if(!p||!G)return!1;var b=a.pageX-g.offsetLeft,c=a.pageY-g.offsetTop,d="1";a.wheelDelta?0<a.wheelDelta&&(d="0"):a.detail&&0>a.detail&&(d="0");i.send("83"+b+"\t"+c+"\t"+d);return!1}function $(a){switch(a){case 33:return 201;case 34:return 209;case 35:return 207;case 36:return 199;case 37:return 203;case 38:return 200;case 39:return 205;case 40:return 208;case 154:return 183;case 45:return 210;
case 46:return 211;case 65406:return 184;case 91:return 91;case 93:return 93;case 27:return 1;case 8:return 14;case 9:return 15;case 13:return 28;case 224:case 17:return 29;case 16:return 54;case 18:return 56;case 20:return 58;case 112:return 59;case 113:return 60;case 114:return 61;case 115:return 62;case 116:return 63;case 117:return 64;case 118:return 65;case 119:return 66;case 120:return 67;case 121:return 68;case 122:return 87;case 123:return 88;case 144:return 69;case 145:return 70}return-1}
function la(a){return"url("+a.data+") "+a.hotX+" "+a.hotY+", default"}var g=document.getElementById("remotectrl"),i=null;g.style.outline="none";var E=0,y=0,H=g.getContext("2d"),d=null,ia=!1,aa=!1,V=!1,v=null;this.context=H;this.fileProgress=null;var j=this,p=!0,G=!1,M=!1,C=!1,w=null,u=null,e=null,U=null,ea=null,o=null,F=-1,z=-1,X=!1,T=null;hi5.browser.isTouch?na():(d=document.createElement("textarea"),d.style.resize="none",d.style.opacity=0,d.style.position="absolute",d.style.margin="0",d.style.border=
"0",d.style.left=0,d.style.top=0,d.style.width=E+"px",d.style.height=y+"px",d.style.zIndex=88,d.style.cursor="default",g.parentNode.appendChild(d));this.railWin=this.toolbar=null;this.browser=window;this.focused=!1;this.showToolbar=!0;this.setCaretPos=function(){};this.showMessage=function(a){hi5.notifications.notify({msg:a})};this.hideWhenClose=!0;this.setReadOnly=function(a){p=!a};this.setPlayerMode=function(){C=true;j.showToolbar=false;j.setReadOnly(true);j.hideWhenClose=false};this.setTouchpad=
function(a){if(M=a)e||s();else if(e&&e.parentNode){e.parentNode.removeChild(e);e=null}};this.setSize=function(a,b,c){window.scrollTo(0,0);E=a;y=b;g.width=E;g.height=y;u&&u.visible()&&u.dismiss();if(d){d.style.width=E+"px";d.style.height=y+"px"}a=document.documentElement;if(c){T=c;a.style.overflow=c}else a.style.overflow=E<=window.innerWidth&&y<=window.innerHeight?"hidden":"visible"};window.svSurface=this;this.setController=function(a){i=a;hi5.browser.isTouch&&window.addEventListener("orientationchange",
function(a){i.onorientationchange(a);window.scrollTo(0,0)},false)};this.setFileHandler=function(a){if(a){if(!v&&!C){v=a;j.fileProgress=new hi5.ProgressBar(document.getElementById("total"));n();r();B()}}else{v=null;j.fileProgress=null;j.toolbar&&j.toolbar.removeButton("cloud.png");n();r()}};this.disableUpload=function(){document.getElementById("uploadfile").style.visibility="hidden"};this.disableShadow=function(){j.toolbar&&j.toolbar.removeButton("info.png")};this.close=function(){j.removeEvents();
try{n();if(e&&e.parentNode){e.parentNode.removeChild(e);e=null}aa=true;window&&!C&&(window.opener?window.close():this.hide())}catch(a){}};this.setFastCopy=function(a){ia=a};this.setConnected=function(a){G=a};this.drawLicense=function(a){var b=a.charAt(0);H.font="12pt Arial";H.fillStyle=b=="W"?"red":"black";a=a.substring(1);H.fillText(a,10,y-24)};this.drawText=function(a){H.font="18pt Arial";H.fillStyle="black";H.fillText(a,20,50)};this.showPDF=function(a){var b=document.createElement("div");b.style.backgroundColor=
"white";b.style.width=hi5.browser.isTouch?"30%":"95%";b.style.height=hi5.browser.isTouch?"4elm":"90%";b.innerHTML=hi5.browser.isTouch?'<p style="text-align:center;line-height:4em"><a href="'+a+'" target="_blank">Your document is ready.</a></p>':'<iframe src="'+a+'" width="100%" height="100%"><html><body marginwidth="0" marginheight="0"><embed width="100%" height="100%" name="plugin" src="'+a+'" type="application/pdf"></body></html></iframe>';document.documentElement.appendChild(b);(new hi5.Lightbox(b)).show()};
this.hide=function(){if(j.hideWhenClose){g.height=1;g.width=1}if(d!=null)d.style.visibility="hidden"};this.copyToClip=function(a){var b=N();"innerText"in b?b.innerText=a:b.innerHTML=a.replace(/\r\n/g,"<br/>");try{b.focus();document.execCommand("selectAll",false,null);document.execCommand("copy",false,null)}catch(c){}finally{b.parentNode.removeChild(b);d.focus();window.scrollTo(0,0)}};this.fullScreen=function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)};this.removeEvents=function(){if(document){document.oncontextmenu=
null;document.onselectstart=null;document.documentElement.style.overflow="visible"}if(window){window.removeEventListener("beforeunload",J,false);window.removeEventListener("focus",t,false);window.onresize=null;try{if(w&&w.parentNode){w.parentNode.removeChild(w);w=null}d&&d.parentNode&&d.parentNode.removeChild(d);w&&w.parentNode&&w.parentNode.removeChild(w)}catch(a){}}};this.refreshFiles=function(){u&&u.visible()&&A(".",u)};this.processLink=function(a){j.toolbar.addButton(hi5.appcfg&&hi5.appcfg.img&&
hi5.appcfg.img.info?hi5.appcfg.img.info:"info.png",function(b){window.open(a);b.target.parentNode.removeChild(b.target)}).title=a;j.toolbar.startFade()};this.setUnicode=function(a){if(d)if(a){d.onkeydown=P;d.onkeyup=P}else{d.onkeydown=S;d.onkeyup=S}};this.run=function(a){window.scrollTo(0,0);n();r();C||ma();if(hi5.browser.isTouch){g.tabIndex=2;if(!C){ea=new f(j,g);g.addEventListener("touchstart",x,false);g.addEventListener("touchend",x,false);g.addEventListener("touchmove",x,false);g.addEventListener("touchcancel",
x,false);a=function(a){h(a)};g.addEventListener("gesturestart",a,false);g.addEventListener("gesturechange",a,false);g.addEventListener("gestureend",a,false)}g.focus()}else{if(!C){d.addEventListener("mousemove",sa,false);d.addEventListener("mousedown",ra,false);d.addEventListener("mouseup",ta,false);d.addEventListener("mousewheel",ka,true);d.addEventListener("DOMMouseScroll",ka,true);d.addEventListener("paste",qa,false);d.addEventListener("copy",ha,false);d.addEventListener("cut",ha,false)}if(a){d.onkeydown=
P;d.onkeyup=P}else{d.onkeydown=S;d.onkeyup=S}I(d);d.focus()}this.drawText(__svi18n.wait)};var pa={"&euro;":"\ufffd","&nbsp;":" ","&quot;":'"',"&amp;":"&","&lt;":"<","&gt;":">","&iexcl;":"\ufffd","&cent;":"\ufffd","&pound;":"\ufffd","&curren;":"\ufffd","&yen;":"\ufffd","&brvbar;":"\ufffd","&sect;":"\ufffd","&uml;":"\ufffd","&copy;":"\ufffd","&ordf;":"\ufffd","&reg;":"\ufffd"};this.movCursorBy=D;this.moveCursor=O;this.touchstart=function(a){if(M&&a.pointes==1)a.pointes=2;g.focus();switch(a.pointes){case 1:if(a.flick&&
T=="visible"){F=a.screenX;z=a.screenY}else i.send("80"+(a.x-g.offsetLeft)+"\t"+(a.y-g.offsetTop)+"\t0");break;case 2:e||s();W("touchstart",a.screenX,a.screenY,!a.flick);break;case 3:F=a.screenX;z=a.screenY}};this.touchmove=function(a){if(M&&a.pointes==1)a.pointes=2;switch(a.pointes){case 1:if(a.flick&&T=="visible"){window.scrollBy(F-a.screenX,z-a.screenY);F=a.screenX;z=a.screenY}else i.send("82"+(a.x-g.offsetLeft)+"\t"+(a.y-g.offsetTop));break;case 2:W("touchmove",a.screenX,a.screenY,!a.flick);break;
case 3:i.send("83"+(a.x-g.offsetLeft)+"\t"+(a.y-g.offsetTop)+"\t"+(a.screenY-z>0?0:1));F=a.screenX;z=a.screenY}};this.touchend=function(a){if(M&&a.pointes==1)a.pointes=2;switch(a.pointes){case 1:O(a.x,a.y,true);(!a.flick||T=="hidden")&&i.send("81"+(a.x-g.offsetLeft)+"\t"+(a.y-g.offsetTop)+"\t0");break;case 2:W("touchend",a.screenX,a.screenY,!a.flick);break;case 3:if(!a.moved){if(j.toolbar)j.toolbar.style.display="block";o&&o.focus()}}};this.flick=function(a){switch(a.from){case 4:console.log("flick from botton");
i.send("840\t209");i.send("8449152\t209");break;case 2:console.log("flick from top");i.send("840\t201");i.send("8449152\t201")}};this.longpress=function(a){if(M)a.pointes=2;switch(a.pointes){case 1:O(a.x,a.y);i.send("80"+a.x+"\t"+a.y+"\t2");i.send("81"+a.x+"\t"+a.y+"\t2");break;case 2:i.send("80"+e.scrX+"\t"+e.scrY+"\t2");i.send("81"+e.scrX+"\t"+e.scrY+"\t2")}};var Z=-1!=navigator.platform.indexOf("Mac"),R=0,ja=0;this.writeScancode=k;var L=!1;this.mouseWheel=function(a,b,c){i.send("83"+a+"\t"+b+"\t"+
(c?1:0))};this.setCursor=function(a){U=a;if(!hi5.browser.isOpera){if(e){e.src=a.data;e.hotX=a.hotX;e.hotY=a.hotY}d?d.style.cursor=la(a):g.style.cursor=la(a)}};this.setVisible=function(a,b){var c=a?"visible":"hidden";typeof b=="number"?setTimeout(function(){g.style.visibility=c},b):g.style.visibility=c}}svGlobal.LocalInterface=LocalInterface;
function initDragDrop(f,s){function n(f){if(1!=f.length)alert("Please one file only");else{var n=f[0],f=n.name,I=f.length;if(4<I&&".rdp"==f.substring(I-4).toLowerCase()){var t=new FileReader,A=!1;t.onload=function(f){var l=f.target.result;if(null!=l){var r=s,f=r.elements,B=l.split("\r\n");2>B.length&&(B=l.split("\n"));if(2>B.length)f=!1;else{var l=document.getElementById("gateway"),q=l.value;r.reset();l.value=q;r=0;for(l=B.length;r<l;r++){var h=B[r],q=h.indexOf(":"),D=h.substring(0,q),h=h.substring(q+
3),D=D.toLowerCase();switch(D){case "full address":q=h.indexOf(":");0<q?(f.server.value=h.substring(0,q),f.port.value=h.substring(q+1)):f.server.value=h;break;case "username":f.user.value=h;break;case "domain":f.domain.value=h;break;case "connect to console":f.useConsole.checked="0"!=h;break;case "desktopwidth":f.width.value=h;break;case "desktopheight":f.height.value=h;break;case "session bpp":f.server_bpp.value=h;break;case "audiomode":f.playSound.value=h;break;case "alternate shell":0<h.length&&
(f.command.value=h,document.getElementById("app").checked||(document.getElementById("shell").checked=!0));break;case "shell working directory":f.directory=h;break;case "redirectclipboard":f.mapClipboard.checked="0"!=h;break;case "redirectprinters":f.mapPrinter.checked="0"!=h;break;case "server port":0<h.length&&(f.port.value=h);break;case "disable wallpaper":f.background.checked="0"==h;break;case "disable themes":f.styles.checked="0"==h;case "disable menu anims":f.animation.checked="0"==h;break;case "disable full window drag":f.contents.checked=
"0"==h;break;case "allow font smoothing":f.smoothfont.checked="0"!=h;break;case "allow desktop composition":f.composition.checked="0"!=h;break;case "bitmapcachepersistenable":f.bitmap.checked="0"!=h;break;case "remoteapplicationprogram":f.exe.value=h;break;case "remoteapplicationcmdline":f.args.value=h;break;case "remoteapplicationmode":document.getElementById("app").checked="1"==h;break;case "loadbalanceinfo":f.loadBalanceInfo.value=h}}f=!0}!f&&!A&&(A=!0,t.readAsText(n))}};t.readAsText(n,"UTF-16LE")}else alert("Sorry, Please .rdp file only")}}
function N(f){n(f.target.files)}if("FileReader"in window){var t=f.style.backgroundColor,J=document.getElementById("rdpfile");J&&J.addEventListener("change",N,!1);f.addEventListener("dragover",function(l){l.stopPropagation();l.preventDefault();f.style.backgroundColor="yellow"},!1);f.addEventListener("dragleave",function(l){l.stopPropagation();l.preventDefault();f.style.backgroundColor=t},!1);f.addEventListener("drop",function(l){l.stopPropagation();l.preventDefault();f.style.backgroundColor=t;n(l.dataTransfer.files)},
!1)}}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=function(f,s){"FileReader"in window&&(f.__oldColor=f.style.backgroundColor,f.addEventListener("dragover",function(n){n.stopPropagation();n.preventDefault();"0"==f.style.opacity&&(f.style.opacity="0.611");f.style.backgroundColor="yellow"},!1),f.addEventListener("dragleave",function(n){n.stopPropagation();n.preventDefault();"0.611"==f.style.opacity&&(f.style.opacity="0");f.style.backgroundColor=f.__oldColor},!1),f.addEventListener("drop",function(n){n.stopPropagation();n.preventDefault();
"0.611"==f.style.opacity&&(f.style.opacity="0");f.style.backgroundColor=f.__oldColor;s(n.dataTransfer.files)},!1))};window.addEventListener("load",function(){for(var f=document.getElementsByClassName("ver"),s=f.length,n=0;n<s;n++)f[n].innerHTML=svGlobal.version},!1);
